# Generated by Django 3.2.9 on 2021-12-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cerbere_uid",
            field=models.IntegerField(null=True),
        ),
    ]
