# Generated by Django 3.2.11 on 2022-02-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_cerbere_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="administrateur_de_compte",
            field=models.BooleanField(default=False),
        ),
    ]
