# Generated by Django 3.2.12 on 2022-03-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_administrateur_de_compte"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telephone",
            field=models.CharField(max_length=25, null=True),
        ),
    ]
