# Generated by Django 3.2.12 on 2022-03-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_telephone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferences_email",
            field=models.CharField(
                choices=[
                    ("TOUS", "Tous les emails"),
                    ("PARTIEL", "Emails des conventions instruites"),
                    ("AUCUN", "Aucun email"),
                ],
                default="TOUS",
                max_length=25,
            ),
        ),
    ]
