# Generated by Django 3.2.13 on 2022-05-31 08:51

from django.db import migrations

from users.type_models import EmailPreferences


def set_user_email_preference(apps, schema_editor):
    User = apps.get_model("users", "User")

    User.objects.filter(preferences_email__isnull=True).update(
        preferences_email=EmailPreferences.PARTIEL
    )
    User.objects.filter(preferences_email="").update(
        preferences_email=EmailPreferences.PARTIEL
    )


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_alter_user_filtre_departements"),
    ]

    operations = [
        migrations.RunPython(set_user_email_preference, migrations.RunPython.noop),
    ]
