# Generated by Django 3.2.13 on 2022-05-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_filtre_departements"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cerbere_login",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
