# Generated by Django 3.2.13 on 2022-06-03 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20220531_1051"),
        ("users", "0010_user_cerbere_login"),
    ]

    operations = []
