# Generated by Django 3.2.14 on 2022-08-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_merge_0010_auto_20220531_1051_0010_user_cerbere_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="typologie",
            field=models.CharField(
                choices=[
                    ("INSTRUCTEUR", "Instructeur"),
                    ("BAILLEUR", "Bailleur"),
                    ("ADMINISTRATEUR", "administrateur"),
                ],
                default="BAILLEUR",
                max_length=25,
            ),
        ),
    ]
