# Generated by Django 3.2.14 on 2022-09-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_role_typologie"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="perimetre_departement",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="role",
            name="perimetre_region",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
