# Generated by Django 4.1.1 on 2022-10-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_user_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferences_email",
            field=models.CharField(
                choices=[
                    ("TOUS", "Tous les emails"),
                    ("PARTIEL", "Emails des conventions instruites"),
                    ("AUCUN", "Aucun email"),
                ],
                default="PARTIEL",
                max_length=25,
            ),
        ),
    ]
