# Generated by Django 4.1.7 on 2023-02-21 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_historicalrole"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluser",
            name="last_login",
        ),
    ]
