# Generated by Django 4.1.7 on 2023-03-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_remove_historicaluser_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="read_popup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="read_popup",
            field=models.BooleanField(default=False),
        ),
    ]
