# Generated by Django 4.1.7 on 2023-03-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_historicaluser_read_popup_user_read_popup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalrole",
            name="typologie",
            field=models.CharField(
                choices=[
                    ("INSTRUCTEUR", "Instructeur"),
                    ("BAILLEUR", "Bailleur"),
                    ("ADMINISTRATEUR", "Administrateur"),
                ],
                default="BAILLEUR",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="typologie",
            field=models.CharField(
                choices=[
                    ("INSTRUCTEUR", "Instructeur"),
                    ("BAILLEUR", "Bailleur"),
                    ("ADMINISTRATEUR", "Administrateur"),
                ],
                default="BAILLEUR",
                max_length=25,
            ),
        ),
    ]
