# Generated by Django 4.1.7 on 2023-03-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "instructeurs",
            "0012_rename_signature_label_extra_administration_signature_bloc_signature",
        ),
        ("bailleurs", "0018_bailleur_signataire_bloc_signature"),
        ("users", "0022_alter_historicalrole_typologie_alter_role_typologie"),
    ]

    operations = [
        # Remove duplicates first
        migrations.RunSQL(
            sql="""
delete from
users_role r
where not exists(
    select ur.id
    from (
        select distinct on (ur.typologie, ur.bailleur_id, ur.administration_id, ur.user_id) ur.id
        from users_role ur
    ) ur
    where ur.id = r.id
)
        """
        ),
        migrations.AlterUniqueTogether(
            name="role",
            unique_together={("typologie", "bailleur", "administration", "user")},
        ),
    ]
