# Generated by Django 4.2 on 2023-04-26 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_alter_role_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluser",
            name="read_popup",
        ),
        migrations.RemoveField(
            model_name="user",
            name="read_popup",
        ),
    ]
