# Generated by Django 4.2.11 on 2024-05-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial_squashed_0024_remove_read_popup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaluser",
            name="administrateur_de_compte",
        ),
        migrations.RemoveField(
            model_name="user",
            name="administrateur_de_compte",
        ),
    ]
