# Generated by Django 4.2.3 on 2023-08-07 15:16

from django.db import migrations
from django.db.models import Count


def clear_siap_users_from_standalone(apps, schema_editor):
    User = apps.get_model("users", "User")
    duplicates = (
        User.objects.values("email")
        .annotate(email_count=Count("email"))
        .filter(email_count__gt=1)
    )
    for duplicate in duplicates:
        print(duplicate)

    print(f"{len(duplicates)} vont être supprimés.")
    duplicates.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_remove_read_popup"),
    ]

    operations = [migrations.RunPython(clear_siap_users_from_standalone)]
