# Generated by Django 5.1.5 on 2025-04-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_additionalemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="secondary_email",
            field=models.EmailField(blank=True, max_length=264),
        ),
        migrations.AddField(
            model_name="user",
            name="secondary_email",
            field=models.EmailField(blank=True, max_length=264),
        ),
        migrations.DeleteModel(
            name="AdditionalEmail",
        ),
    ]
