version: "3"
services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=apilos
      - POSTGRES_PASSWORD=apilos
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      # Use: delegated to get better performances on docker write workloads where the sync with the host is not mandatory
      - ./pgdata:/var/lib/postgresql/data:delegated
    ports:
      - 5433:5432
  redis:
    image: redis:7.0
    restart: always
    expose:
      - 6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-data:/data:delegated
      - ./redis.conf:/usr/local/etc/redis/redis.conf
  apilos: &apilos
    build:
      context: .
      args:
        - IPYTHON_AUTORELOAD=${IPYTHON_AUTORELOAD:-}
    volumes:
      # Use: cached to get better performances on read-heavy workloads, typically here the mounted code will be edited on the host
      - .:/code:cached
    ports:
      - "8001:8000"
    restart: on-failure # Automatically restart on failure (if PG not up yet)
    depends_on:
      - postgres
      - redis

  dramatiq:
    <<: *apilos
    command: python manage.py rundramatiq --reload
    ports: []


volumes:
  cache:
    driver: local
  data:
    driver: local
  pgdata:
