version: "3"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=apilos
      - POSTGRES_PASSWORD=apilos
      - POSTGRES_MULTIPLE_DATABASES=apilos-test
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  data:
    driver: local
  pgdata:
