version: "3"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=apilos
      - POSTGRES_PASSWORD=apilos
      - POSTGRES_MULTIPLE_DATABASES=apilos-test
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
  apilos:
    build: .
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - postgres

volumes:
  data:
    driver: local
  pgdata:
