[tool.coverage.run]
omit = [
    "*/__init__.py",
    "*/tests/*",
    "*/migrations/*",
    "ecoloweb/*",
    "programmes/management/commands/import_galion.py",
    # TODO: add tests on the following modules and remove them from this list
    "conventions/services/upload_objects.py",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"

[tool.ruff]
select = [
    "F",   # Pyflakes
    "E",   # pycodestyle
    "W",   # pycodestyle
    "C90", # mccabe
    "I",   # isort
    "UP",  # pyupgrade
    # TODO: apply the following rules
    # "N",   # pep8-naming
    # "BLE", # flake8-blind-except
    # "FBT", # flake8-boolean-trap
    # "B",   # flake8-bugbear
    # "C4",  # flake8-comprehensions
    # "ISC", # flake8-implicit-str-concat
    # "T20", # flake8-print
    "Q",   # flake8-quotes
    "TID", # flake8-tidy-imports
    "PGH", # pygrep-hooks
    "INP", # flake8-no-pep420
]
line-length = 120
show-fixes = true
unfixable = ["B"]
target-version = "py310"
exclude = [
    ".venv",
    "bin",
    "documents",
    "node_modules",
    "staticfiles",
    "templates",

]

[tool.ruff.extend-per-file-ignores]
"__init__.py" = ["F401", "F403"]
"scripts/*.py" = ["INP001"]
"**/migrations/*.py" = ["E501"]
# TODO: ignored because of low coverage, fix and remove
"conventions/services/upload_objects.py" = ["UP"]
"conventions/services/recapitulatif.py" = ["UP"]
"conventions/views/avenants.py" = ["I001"]
# TODO: changing imports order make tests fail, fix and remove
"ecoloweb/services/__init__.py" = ["I001"]

[tool.ruff.lint.mccabe]
max-complexity = 20 # TODO: very high value, reduce to 10

[tool.ruff.isort]
case-sensitive = true
known-third-party = [
    "boto3",
    "botocore",
    "celery",
    "decouple",
    "dj_database_url",
    "django_cas_ng",
    "django",
    "docx",
    "docxtpl",
    "drf_spectacular",
    "openpyxl",
    "rest_framework_simplejwt",
    "rest_framework",
    "sentry_sdk",
    "simple_history",
    "storages",
    "zipfile",
]
split-on-trailing-comma = true
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
