# Generated by Django 3.2.5 on 2021-07-06 14:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bailleurs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programme",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("nom", models.CharField(max_length=255)),
                ("code_postal", models.CharField(max_length=10)),
                ("ville", models.CharField(max_length=255)),
                ("adresse", models.CharField(max_length=255)),
                ("nb_logements", models.IntegerField()),
                (
                    "type_operation",
                    models.CharField(
                        choices=[
                            ("NEUF", "Neuf"),
                            ("ACQUIS", "Acquis amélioré"),
                            ("DEMEMBREMENT", "Démembrement"),
                            ("USUFRUIT", "Usufruit"),
                            ("VEFA", "VEFA"),
                        ],
                        default="NEUF",
                        max_length=15,
                    ),
                ),
                ("anru", models.BooleanField(default=False)),
                ("nb_logement_non_conventionne", models.IntegerField()),
                ("nb_locaux_commerciaux", models.IntegerField()),
                ("nb_bureaux", models.IntegerField()),
                ("vendeur", models.TextField()),
                ("acquereur", models.TextField()),
                ("date_acte_notarie", models.DateField()),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("mis_a_jour_le", models.DateTimeField(auto_now=True)),
                (
                    "bailleur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bailleurs.bailleur",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("can_edit_programme", "Créer ou mettre à jour un programme"),
                ),
            },
        ),
    ]
