# Generated by Django 3.2.5 on 2021-07-06 16:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bailleurs', '0001_initial'),
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('numero', models.IntegerField(null=True)),
                ('financement', models.CharField(choices=[('PLUS', 'PLUS'), ('PLAI', 'PLAI'), ('PLUS-PLAI', 'PLUS-PLAI'), ('PLS', 'PLS')], default='PLUS', max_length=25)),
                ('volumes', models.TextField(null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bailleurs.bailleur')),
            ],
        ),
        migrations.AlterModelOptions(
            name='programme',
            options={},
        ),
        migrations.AddField(
            model_name='programme',
            name='date_achat',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='date_achevement',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='date_achevement_previsible',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='permis_construire',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='reference_notaire',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='reference_publication_acte',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='acquereur',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='adresse',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='code_postal',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='date_acte_notarie',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='nb_bureaux',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='nb_locaux_commerciaux',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='nb_logement_non_conventionne',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='nb_logements',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='type_operation',
            field=models.CharField(choices=[('NEUF', 'Neuf'), ('ACQUIS', 'Acquis amélioré'), ('DEMEMBREMENT', 'Démembrement'), ('USUFRUIT', 'Usufruit'), ('VEFA', 'VEFA')], default='NEUF', max_length=25),
        ),
        migrations.AlterField(
            model_name='programme',
            name='vendeur',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='ville',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='TypeStationnement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('typologie', models.CharField(choices=[('GARAGE_AERIEN', 'Garage Aérien'), ('GARAGE_ENTERRE', 'Garage enterré'), ('PLACE_STATIONNEMENT', 'Place stationnement')], default='PLACE_STATIONNEMENT', max_length=25)),
                ('nb_stationnements', models.IntegerField()),
                ('loyer', models.FloatField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bailleurs.bailleur')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.lot')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceCadastrale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nom', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255, null=True)),
                ('numero', models.IntegerField(null=True)),
                ('lieudit', models.CharField(max_length=255, null=True)),
                ('surface', models.FloatField(null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bailleurs.bailleur')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.programme')),
            ],
        ),
        migrations.AddField(
            model_name='lot',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.programme'),
        ),
        migrations.CreateModel(
            name='Logement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('designation', models.CharField(max_length=255)),
                ('typologie', models.CharField(choices=[('T1', 'T1'), ('T2', 'T2'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5 et plus')], default='T1', max_length=25)),
                ('surface_habitable', models.FloatField(null=True)),
                ('surface_annexes', models.FloatField(null=True)),
                ('surface_annexes_retenue', models.FloatField(null=True)),
                ('surface_utile', models.FloatField(null=True)),
                ('loyer_par_metre_carre', models.FloatField(null=True)),
                ('coeficient', models.FloatField(null=True)),
                ('loyer', models.FloatField(null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bailleurs.bailleur')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.lot')),
            ],
        ),
        migrations.CreateModel(
            name='Annexe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('typologie', models.CharField(choices=[('BALCON', 'Balcon'), ('TERRASSE', 'Terrasse'), ('JARDIN', 'Jardin')], default='BALCON', max_length=25)),
                ('surface_hors_surface_retenue', models.FloatField()),
                ('loyer_par_metre_carre', models.FloatField()),
                ('loyer', models.FloatField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('bailleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bailleurs.bailleur')),
                ('logement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmes.logement')),
            ],
        ),
    ]
