# Generated by Django 3.2.5 on 2021-07-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0003_auto_20210726_1100"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="departement",
            field=models.IntegerField(null=True),
        ),
    ]
