# Generated by Django 3.2.5 on 2021-07-27 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructeurs', '0001_initial'),
        ('programmes', '0005_programme_administration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='administration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='instructeurs.administration'),
        ),
    ]
