# Generated by Django 3.2.5 on 2021-07-28 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructeurs", "0001_initial"),
        ("programmes", "0006_alter_programme_administration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="administration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="instructeurs.administration",
            ),
        ),
    ]
