# Generated by Django 3.2.5 on 2021-07-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0007_alter_programme_administration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="programme",
            old_name="numero_gallion",
            new_name="numero_galion",
        ),
    ]
