# Generated by Django 3.2.5 on 2021-09-03 14:07

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0003_alter_bailleur_options"),
        ("programmes", "0012_auto_20210902_1538"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="acte_de_vente",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="edd_volumetrique",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="annexe",
            name="typologie",
            field=models.CharField(
                choices=[
                    ("BALCON", "Balcon"),
                    ("TERRASSE", "Terrasse"),
                    ("JARDIN", "Jardin"),
                    ("CAVE", "Cave"),
                ],
                default="TERRASSE",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="LogementEDD",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("designation", models.CharField(max_length=255)),
                (
                    "financement",
                    models.CharField(
                        choices=[
                            ("PLUS", "PLUS"),
                            ("PLAI", "PLAI"),
                            ("PLAI_ADP", "PLAI_ADP"),
                            ("PLUS-PLAI", "PLUS-PLAI"),
                            ("PLS", "PLS"),
                        ],
                        default="PLUS",
                        max_length=25,
                    ),
                ),
                (
                    "typologie",
                    models.CharField(
                        choices=[
                            ("T1", "T1"),
                            ("T2", "T2"),
                            ("T3", "T3"),
                            ("T4", "T4"),
                            ("T5", "T5 et plus"),
                        ],
                        default="T1",
                        max_length=25,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("mis_a_jour_le", models.DateTimeField(auto_now=True)),
                (
                    "bailleur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bailleurs.bailleur",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="programmes.programme",
                    ),
                ),
            ],
        ),
    ]
