# Generated by Django 3.2.5 on 2021-09-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0013_auto_20210903_1607"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lot",
            name="volumes",
        ),
    ]
