# Generated by Django 3.2.5 on 2021-09-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0014_remove_lot_volumes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programme",
            name="nb_logements",
        ),
        migrations.AddField(
            model_name="lot",
            name="nb_logements",
            field=models.IntegerField(null=True),
        ),
    ]
