# Generated by Django 3.2.5 on 2021-09-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0016_remove_referencecadastrale_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annexe',
            name='typologie',
            field=models.CharField(choices=[
                ('TERRASSE', 'Terrasse'), ('JARDIN', 'Jardin'),
                ('CAVE', 'Cave')], default='TERRASSE', max_length=25),
        ),
        migrations.AlterField(
            model_name='logementedd',
            name='financement',
            field=models.CharField(choices=[
                ('PLUS', 'PLUS'), ('PLAI', 'PLAI'), ('PLAI_ADP', 'PLAI_ADP'),
                ('PLS', 'PLS')], default='PLUS', max_length=25),
        ),
        migrations.AlterField(
            model_name='programme',
            name='type_habitat',
            field=models.CharField(choices=[
                ('SANSOBJET', 'Sans Objet'), ('INDIVIDUEL', 'Individuel'),
                ('COLLECTIF', 'Collectif')], default='INDIVIDUEL', max_length=25),
        ),
        migrations.AlterField(
            model_name='programme',
            name='type_operation',
            field=models.CharField(choices=[
                ('SANSOBJET', 'Sans Objet'), ('NEUF', 'Construction Neuve'),
                ('ACQUIS', 'Acquisition-Amélioration'), ('DEMEMBREMENT', 'Démembrement'),
                ('REHABILITATION', 'Réhabilitation'), ('SANSTRAVAUX', 'Sans travaux'),
                ('USUFRUIT', 'Usufruit'), ('VEFA', 'VEFA')], default='NEUF', max_length=25),
        ),
    ]
