# Generated by Django 3.2.7 on 2021-09-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0018_alter_referencecadastrale_surface"),
    ]

    operations = [
        migrations.RenameField(
            model_name="programme",
            old_name="acte_de_vente",
            new_name="acte_de_propriete",
        ),
        migrations.AddField(
            model_name="programme",
            name="acte_notarial",
            field=models.TextField(null=True),
        ),
    ]
