# Generated by Django 3.2.7 on 2021-09-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0019_auto_20210922_1417"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typestationnement",
            name="typologie",
            field=models.CharField(
                choices=[
                    ("GARAGE_AERIEN", "Garage Aérien"),
                    ("GARAGE_ENTERRE", "Garage enterré"),
                    ("PLACE_STATIONNEMENT", "Place de stationnement"),
                ],
                default="PLACE_STATIONNEMENT",
                max_length=25,
            ),
        ),
    ]
