# Generated by Django 3.2.7 on 2021-09-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0020_alter_typestationnement_typologie"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="edd_classique",
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="mention_publication_edd_classique",
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="mention_publication_edd_volumetrique",
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="programme",
            name="edd_volumetrique",
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
