# Generated by Django 3.2.8 on 2021-10-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0023_auto_20211007_1201"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="reference_cadastrale",
            field=models.TextField(null=True),
        ),
    ]
