# Generated by Django 3.2.9 on 2021-11-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0024_programme_reference_cadastrale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typestationnement",
            name="typologie",
            field=models.CharField(
                choices=[
                    ("GARAGE_AERIEN", "Garage aérien"),
                    ("GARAGE_ENTERRE", "Garage enterré"),
                    ("PLACE_STATIONNEMENT", "Place de stationnement"),
                ],
                default="PLACE_STATIONNEMENT",
                max_length=25,
            ),
        ),
    ]
