# Generated by Django 3.2.9 on 2021-12-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0025_alter_typestationnement_typologie"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="annexe_ateliers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lot",
            name="annexe_balcons",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lot",
            name="annexe_caves",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lot",
            name="annexe_celliers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lot",
            name="annexe_combles",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lot",
            name="annexe_loggias",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lot",
            name="annexe_remises",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lot",
            name="annexe_resserres",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lot",
            name="annexe_sechoirs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lot",
            name="annexe_soussols",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lot",
            name="annexe_terrasses",
            field=models.BooleanField(default=False),
        ),
    ]
