# Generated by Django 3.2.10 on 2021-12-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "programmes",
            "0028_rename_autre_locaux_hors_convention_programme_autres_locaux_hors_convention",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="typestationnement",
            name="typologie",
            field=models.CharField(
                choices=[
                    ("GARAGE_AERIEN", "Garage aérien"),
                    ("GARAGE_ENTERRE", "Garage enterré"),
                    ("PLACE_STATIONNEMENT", "Place de stationnement"),
                    ("PARKING_EXTERIEUR_PRIVATIF", "Parking extérieur privatif"),
                    ("PARKING_SOUSSOL", "Parking en sous-sol ou en superstructure"),
                    ("GARAGE_BOXE_SIMPLE", "Garage boxé simple"),
                    ("GARAGE_BOXE_DOUBLE", "Garage boxé double"),
                ],
                default="PLACE_STATIONNEMENT",
                max_length=35,
            ),
        ),
    ]
