# Generated by Django 3.2.11 on 2022-01-07 14:16

from django.db import migrations, models

from programmes.models import TypeHabitat


def type_habitat_sansobj(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    Programme = apps.get_model("programmes", "Programme")

    for prog in Programme.objects.all().filter(type_habitat="SANSOBJECT"):
        prog.type_habitat = TypeHabitat.COLLECTIF


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0029_alter_typestationnement_typologie"),
    ]

    operations = [
        migrations.RunPython(type_habitat_sansobj),
        migrations.AlterField(
            model_name="programme",
            name="type_habitat",
            field=models.CharField(
                choices=[
                    ("MIXTE", "Mixte"),
                    ("INDIVIDUEL", "Individuel"),
                    ("COLLECTIF", "Collectif"),
                ],
                default="INDIVIDUEL",
                max_length=25,
            ),
        ),
    ]
