# Generated by Django 3.2.11 on 2022-01-19 08:59

from django.db import migrations

from programmes.models import TypeHabitat, TypeOperation, Zone123bis, ZoneABCbis


def normalize_enum_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    Programme = apps.get_model("programmes", "Programme")

    for prog in Programme.objects.all():

        for value, label in ZoneABCbis.choices:
            if (
                prog.zone_abc_bis is not None
                and prog.zone_abc_bis.lower() == label.lower()
            ):
                prog.zone_abc_bis = value
        if prog.zone_abc_bis not in ZoneABCbis.values:
            prog.zone_abc_bis = Programme.zone_abc_bis.field.default

        for value, label in Zone123bis.choices:
            if (
                prog.zone_123_bis is not None
                and prog.zone_123_bis.lower() == label.lower()
            ):
                prog.zone_123_bis = value
        if prog.zone_123_bis not in Zone123bis.values:
            prog.zone_123_bis = Programme.zone_123_bis.field.default

        for value, label in TypeHabitat.choices:
            if (
                prog.type_habitat is not None
                and prog.type_habitat.lower() == label.lower()
            ):
                prog.type_habitat = value
        if prog.type_habitat not in TypeHabitat.values:
            prog.type_habitat = Programme.type_habitat.field.default

        for value, label in TypeOperation.choices:
            if (
                prog.type_operation is not None
                and prog.type_operation.lower() == label.lower()
            ):
                prog.type_operation = value
        if prog.type_operation not in TypeOperation.values:
            prog.type_operation = Programme.type_operation.field.default

        prog.save()
        # VENDEUR


def nothing_to_do(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0032_programme_date_achevement_compile"),
    ]

    operations = [
        migrations.RunPython(normalize_enum_data, nothing_to_do),
    ]
