# Generated by Django 3.2.11 on 2022-01-19 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0033_auto_20220119_0959"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programme",
            name="zone_123",
        ),
        migrations.RemoveField(
            model_name="programme",
            name="zone_abc",
        ),
    ]
