# Generated by Django 3.2.12 on 2022-02-15 16:57

from django.db import migrations, models


def copy_edd_to_lot(apps, schema_editor):
    Convention = apps.get_model("conventions", "Convention")

    for conv in Convention.objects.all():
        programme = conv.programme
        lot = conv.lot
        lot.edd_volumetrique = programme.edd_volumetrique
        lot.edd_classique = programme.edd_classique
        lot.save()


def nothing_to_do(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0035_auto_20220207_1248"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="edd_classique",
            field=models.TextField(max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name="lot",
            name="edd_volumetrique",
            field=models.TextField(max_length=50000, null=True),
        ),
        migrations.RunPython(copy_edd_to_lot, nothing_to_do),
    ]
