# Generated by Django 3.2.12 on 2022-02-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0037_lot_type_habitat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programme",
            name="type_habitat",
        ),
    ]
