# Generated by Django 3.2.12 on 2022-03-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0038_remove_programme_type_habitat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="adresse",
            field=models.TextField(null=True),
        ),
    ]
