# Generated by Django 3.2.12 on 2022-04-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0040_rename_acte_notarial_programme_certificat_adressage"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="lgts_mixite_sociale_negocies",
            field=models.IntegerField(default=0),
        ),
    ]
