# Generated by Django 3.2.12 on 2022-05-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0042_lot_loyer_derogatoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='effet_relatif',
            field=models.TextField(null=True),
        ),
    ]
