# Generated by Django 3.2.13 on 2022-07-08 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0046_auto_20220627_1521"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="financement",
            field=models.CharField(
                choices=[
                    ("PLUS", "PLUS"),
                    ("PLAI", "PLAI"),
                    ("PLAI_ADP", "PLAI_ADP"),
                    ("PLUS-PLAI", "PLUS-PLAI"),
                    ("PLS", "PLS"),
                    ("PSH", "PSH"),
                    ("PALULOS", "PALULOS"),
                ],
                default="PLUS",
                max_length=25,
            ),
        ),
    ]
