# Generated by Django 3.2.13 on 2022-07-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0047_alter_lot_financement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="programme",
            old_name="zone_123_bis",
            new_name="zone_123",
        ),
        migrations.RenameField(
            model_name="programme",
            old_name="zone_abc_bis",
            new_name="zone_abc",
        ),
    ]
