# Generated by Django 4.1.3 on 2022-11-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0053_alter_logement_typologie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annexe",
            name="bailleur",
        ),
        migrations.RemoveField(
            model_name="logement",
            name="bailleur",
        ),
        migrations.RemoveField(
            model_name="logementedd",
            name="bailleur",
        ),
        migrations.RemoveField(
            model_name="lot",
            name="bailleur",
        ),
        migrations.RemoveField(
            model_name="referencecadastrale",
            name="bailleur",
        ),
        migrations.RemoveField(
            model_name="typestationnement",
            name="bailleur",
        ),
    ]
