# Generated by Django 4.1.3 on 2022-11-25 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0055_alter_logementedd_financement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logementedd",
            name="programme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logementedds",
                to="programmes.programme",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="programme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lots",
                to="programmes.programme",
            ),
        ),
        migrations.AlterField(
            model_name="referencecadastrale",
            name="programme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referencecadastrales",
                to="programmes.programme",
            ),
        ),
    ]
