# Generated by Django 4.1.4 on 2022-12-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "programmes",
            "0058_programme_date_autorisation_hors_habitat_inclusif_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="surface_habitable_totale",
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name="logement",
            name="typologie",
            field=models.CharField(
                choices=[
                    ("T1", "T1"),
                    ("T1bis", "T1bis"),
                    ("T1prime", "T1'"),
                    ("T2", "T2"),
                    ("T3", "T3"),
                    ("T4", "T4"),
                    ("T5", "T5"),
                    ("T6", "T6"),
                    ("T7", "T7"),
                ],
                default="T1",
                max_length=25,
            ),
        ),
    ]
