# Generated by Django 4.1.3 on 2022-12-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0060_lot_foyer_residence_dependance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="locauxcollectifs",
            name="type_local",
            field=models.CharField(max_length=255),
        ),
    ]
