# Generated by Django 4.1.5 on 2023-01-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0062_alter_annexe_typologie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logement",
            name="typologie",
            field=models.CharField(
                choices=[
                    ("T1", "T1"),
                    ("T1bis", "T1 bis"),
                    ("T1prime", "T1'"),
                    ("T2", "T2"),
                    ("T3", "T3"),
                    ("T4", "T4"),
                    ("T5", "T5"),
                    ("T6", "T6"),
                    ("T7", "T7"),
                ],
                default="T1",
                max_length=25,
            ),
        ),
    ]
