# Generated by Django 4.1.5 on 2023-01-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0063_alter_logement_typologie"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="date_residence_agrement",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="date_residence_argement_gestionnaire_intermediation",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="departement_residence_agrement",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="programme",
            name="departement_residence_argement_gestionnaire_intermediation",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
