# Generated by Django 4.1.5 on 2023-01-31 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0064_programme_date_residence_agrement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="ville_signature_residence_argement_gestionnaire_intermediation",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
