# Generated by Django 4.1.5 on 2023-02-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0066_add_logement_surface_corrigee"),
    ]

    operations = [
        migrations.RunSQL(
            sql="drop view if exists v_convention_departement",
            reverse_sql="""
create or replace view v_convention_departement
as
select
    c.id,
    asd.id as departement_id
from conventions_convention c
    inner join programmes_programme pp on c.programme_id = pp.id
    inner join apilos_settings_departement asd on substr(pp.code_postal, 1, 2) = asd.code_insee or substr(pp.code_postal, 1, 3) = asd.code_insee
""",
        ),
        migrations.AlterField(
            model_name="programme",
            name="adresse",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="programme",
            name="code_postal",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="programme",
            name="ville",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
