# Generated by Django 4.1.6 on 2023-02-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0068_alter_logement_loyer_par_metre_carre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logement",
            name="coeficient",
            field=models.DecimalField(
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Coefficient propre au logement",
            ),
        ),
        migrations.AlterField(
            model_name="logement",
            name="loyer",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
