# Generated by Django 4.1.6 on 2023-02-20 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0069_alter_logement_coeficient_alter_logement_loyer"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndiceEvolutionLoyer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("annee", models.IntegerField()),
                (
                    "nature_logement",
                    models.TextField(
                        choices=[
                            ("LOGEMENTSORDINAIRES", "Logements ordinaires"),
                            ("AUTRE", "Autres logements foyers"),
                            ("HEBERGEMENT", "Hébergement"),
                            ("RESISDENCESOCIALE", "Résidence sociale"),
                            (
                                "PENSIONSDEFAMILLE",
                                "Pensions de famille (Maisons relais)",
                            ),
                            ("RESIDENCEDACCUEIL", "Résidence d'accueil"),
                            ("RESIDENCEUNIVERSITAIRE", "Résidence universitaire"),
                            ("RHVS", "RHVS"),
                        ],
                        default="AUTRE",
                    ),
                ),
                ("differentiel", models.FloatField()),
            ],
        ),
        migrations.AddIndex(
            model_name="indiceevolutionloyer",
            index=models.Index(
                fields=["annee", "nature_logement"], name="annee_nature_logement"
            ),
        ),
    ]
