# Generated by Django 4.1.7 on 2023-02-22 11:19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0069_alter_logement_coeficient_alter_logement_loyer"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndiceEvolutionLoyer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("is_loyer", models.BooleanField(default=True)),
                ("annee", models.IntegerField()),
                (
                    "nature_logement",
                    models.TextField(
                        choices=[
                            ("LOGEMENTSORDINAIRES", "Logements ordinaires"),
                            ("AUTRE", "Autres logements foyers"),
                            ("HEBERGEMENT", "Hébergement"),
                            ("RESISDENCESOCIALE", "Résidence sociale"),
                            (
                                "PENSIONSDEFAMILLE",
                                "Pensions de famille (Maisons relais)",
                            ),
                            ("RESIDENCEDACCUEIL", "Résidence d'accueil"),
                            ("RESIDENCEUNIVERSITAIRE", "Résidence universitaire"),
                            ("RHVS", "RHVS"),
                        ],
                        default="LOGEMENTSORDINAIRES",
                        null=True,
                    ),
                ),
                ("evolution", models.FloatField()),
            ],
        ),
        migrations.AddIndex(
            model_name="indiceevolutionloyer",
            index=models.Index(
                fields=["annee", "is_loyer", "nature_logement"],
                name="idx_annee_and_type",
            ),
        ),
    ]
