# Generated by Django 4.1.7 on 2023-03-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0071_extend_logement_max_digits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="mention_publication_edd_classique",
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="programme",
            name="mention_publication_edd_volumetrique",
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
