# Generated by Django 4.1.7 on 2023-04-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programmes", "0074_programme_surface_corrigee_totale_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="surface_locaux_collectifs_residentiels",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Surface des locaux collectifs résidentiels",
            ),
        ),
    ]
