# Generated by Django 4.1.7 on 2023-04-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0075_alter_lot_surface_locaux_collectifs_residentiels"),
    ]

    operations = [
        migrations.RunSQL(
            "truncate table programmes_indiceevolutionloyer", reverse_sql=""
        ),
        migrations.AddField(
            model_name="indiceevolutionloyer",
            name="date_debut",
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name="indiceevolutionloyer",
            name="date_fin",
            field=models.DateField(),
        ),
    ]
