# Generated by Django 4.2.1 on 2023-05-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programmes", "0077_auto_20230515_1912"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="programme",
            index=models.Index(
                fields=["-date_achevement_compile"],
                name="programmes__date_ac_4ced67_idx",
            ),
        ),
    ]
