# Generated by Django 4.2.3 on 2023-07-29 08:05

import csv
from pathlib import Path

from django.conf import settings
from django.db import migrations

OLD_KEY = "Ancien Code Officiel"
CURRENT_KEY = "Code Courant Officiel"

# Source : https://public.opendatasoft.com/explore/dataset/georef-france-matching-code/export/?flg=fr&disjunctive.abbr_type&refine.abbr_type=REG noqa


def remove_deprecated_region_codes(apps, schema_editor):
    Programme = apps.get_model("programmes", "Programme")
    region_reference = Path(
        settings.BASE_DIR / "csv" / "georef-france-matching-code.csv"
    )
    updated_programmes = []
    with open(region_reference, newline="", encoding="utf-8") as csvfile:
        reader = csv.DictReader(csvfile, delimiter=";")
        for row in reader:
            if row[OLD_KEY] != row[CURRENT_KEY]:
                programmes_to_update = Programme.objects.filter(
                    code_insee_region=row[OLD_KEY]
                )
                programmes_to_update.update(code_insee_region=row[CURRENT_KEY])
                updated_programmes.extend(programmes_to_update)

    print(  # noqa: T201
        f"\n {len(updated_programmes)} programmes ont été mis à jour avec succès"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("programmes", "0079_deduplication_programmes_ecolo"),
    ]

    operations = [
        migrations.RunPython(remove_deprecated_region_codes, migrations.RunPython.noop),
    ]
