# Generated by Django 4.2.5 on 2023-10-12 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programmes", "0080_auto_20230729_1005"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programme",
            name="date_residence_agrement",
        ),
        migrations.RemoveField(
            model_name="programme",
            name="departement_residence_agrement",
        ),
    ]
