# Generated by Django 4.2.5 on 2023-11-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programmes", "0081_remove_programme_date_residence_agrement_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="programme",
            index=models.Index(
                fields=["numero_galion"], name="programme_numero_galion_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programme",
            index=models.Index(fields=["ville"], name="programme_ville_idx"),
        ),
        migrations.AddIndex(
            model_name="programme",
            index=models.Index(
                fields=["code_postal"], name="programme_code_postal_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="programme",
            index=models.Index(fields=["nom"], name="programme_nom_idx"),
        ),
    ]
