# Generated by Django 4.2.5 on 2023-11-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programmes", "0082_programme_add_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logementedd",
            name="financement",
            field=models.CharField(
                choices=[
                    ("PLUS", "PLUS"),
                    ("PLUS_CD", "PLUS_CD"),
                    ("PLAI", "PLAI"),
                    ("PLS", "PLS"),
                    ("SANS_FINANCEMENT", "Sans Financement"),
                ],
                default="PLUS",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="financement",
            field=models.CharField(
                choices=[
                    ("PLUS", "PLUS"),
                    ("PLUS_CD", "PLUS_CD"),
                    ("PLAI", "PLAI"),
                    ("PLAI_ADP", "PLAI_ADP"),
                    ("PLUS-PLAI", "PLUS-PLAI"),
                    ("PLS", "PLS"),
                    ("PSH", "PSH"),
                    ("PALULOS", "PALULOS"),
                    ("SANS_FINANCEMENT", "Sans Financement"),
                ],
                default="PLUS",
                max_length=25,
            ),
        ),
    ]
