# Generated by Django 4.2.9 on 2024-01-25 09:18

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programmes", "0084_programme_edd_stationnements"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="programme",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector("ville", config="french"),
                name="search_vector_ville_idx",
            ),
        ),
    ]
