# Generated by Django 4.2.9 on 2024-01-29 16:33

from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programmes", "0085_programme_search_vector_ville_idx"),
    ]

    operations = [
        BtreeGinExtension(),
    ]
