# Generated by Django 4.2.9 on 2024-01-29 19:04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programmes", "0086_btree_gin_extension"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="programme",
            name="search_vector_ville_idx",
        ),
        migrations.AddField(
            model_name="programme",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="programme",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="search_vector_programme_idx"
            ),
        ),
    ]
