# Generated by Django 4.2.9 on 2024-01-29 19:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programmes", "0087_programme_search_vector"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP TRIGGER IF EXISTS search_vector_trigger_programme ON programmes_programme;
                DROP FUNCTION IF EXISTS search_vector_programme_func;

                CREATE FUNCTION search_vector_programme_func() RETURNS trigger AS $$
                begin
                new.search_vector :=
                    setweight(to_tsvector('pg_catalog.french', coalesce(new.nom,'')), 'A') ||
                    setweight(to_tsvector('pg_catalog.french', coalesce(new.ville,'')), 'B') ||
                    setweight(to_tsvector('pg_catalog.french', coalesce(new.adresse,'')), 'C') ||
                    setweight(to_tsvector('pg_catalog.french', coalesce(new.code_postal,'')), 'C');
                return new;
                end
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER search_vector_trigger_programme
                BEFORE INSERT OR UPDATE OF nom, adresse, code_postal, ville
                ON programmes_programme
                FOR EACH ROW EXECUTE FUNCTION search_vector_programme_func();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS search_vector_trigger_programme ON programmes_programme;
                DROP FUNCTION IF EXISTS search_vector_programme_func;
            """,
        ),
    ]
