# Generated by Django 4.2.9 on 2024-02-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apilos_settings", "0005_alter_departement_code_insee_region"),
        ("programmes", "0088_programme_search_vector_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="indiceevolutionloyer",
            name="departements",
            field=models.ManyToManyField(
                blank=True,
                related_name="departements",
                to="apilos_settings.departement",
                verbose_name="Départements concernés",
            ),
        ),
    ]
