# Generated by Django 4.2.9 on 2024-02-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programmes", "0089_indiceevolutionloyer_departements"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="reassign_command_old_admin_backup",
            field=models.CharField(default=None, null=True),
        ),
    ]
