# Generated by Django 4.2.10 on 2024-05-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0093_alter_typestationnement_typologie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="financement",
            field=models.CharField(
                choices=[
                    ("PLUS", "PLUS"),
                    ("PLUS_CD", "PLUS_CD"),
                    ("PLAI", "PLAI"),
                    ("PLAI_ADP", "PLAI_ADP"),
                    ("PLUS-PLAI", "PLUS-PLAI"),
                    ("PLS", "PLS"),
                    ("PSH", "PSH"),
                    ("PALULOS", "PALULOS"),
                    ("SANS_FINANCEMENT", "Sans Financement"),
                    ("LLS", "LLS"),
                    ("LLTS", "LLTS"),
                    ("LLTSA", "LLTSA"),
                    ("PLUS_DOM", "PLUS_DOM"),
                ],
                default="PLUS",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="zone_abc",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("Abis", "Abis"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C", "C"),
                    ("DROM", "DROM"),
                ],
                default=None,
                max_length=25,
                null=True,
            ),
        ),
    ]
