# Generated by Django 4.2.10 on 2024-04-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0093_alter_typestationnement_typologie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="financement",
            field=models.CharField(
                choices=[
                    ("PLUS", "PLUS"),
                    ("PLUS_CD", "PLUS_CD"),
                    ("PLAI", "PLAI"),
                    ("PLAI_ADP", "PLAI_ADP"),
                    ("PLUS-PLAI", "PLUS-PLAI"),
                    ("PLS", "PLS"),
                    ("PSH", "PSH"),
                    ("PALULOS", "PALULOS"),
                    ("SANS_FINANCEMENT", "Sans Financement"),
                    ("LLS", "LLS"),
                    ("LLTS", "LLTS"),
                    ("LLTSA", "LLTSA"),
                ],
                default="PLUS",
                max_length=25,
            ),
        ),
    ]
