# Generated by Django 4.2.13 on 2024-05-17 09:06

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("programmes", "0093_alter_typestationnement_typologie"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="programme",
            index=models.Index(
                fields=["code_insee_region"], name="programmes__code_insee_reg_idx"
            ),
        ),
        AddIndexConcurrently(
            model_name="programme",
            index=models.Index(
                fields=["code_insee_departement"], name="programmes__code_insee_dep_idx"
            ),
        ),
    ]
