# Generated by Django 4.2.10 on 2024-04-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0094_alter_lot_financement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="zone_abc",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("Abis", "Abis"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C", "C"),
                    ("DROM", "DROM"),
                ],
                default=None,
                max_length=25,
                null=True,
            ),
        ),
    ]
