# Generated by Django 4.2.13 on 2024-05-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0095_programme_numero_operation_pour_recherche"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="seconde_vie",
            field=models.BooleanField(default=False),
        ),
    ]
