# Generated by Django 4.2.13 on 2024-06-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0096_programme_seconde_vie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="seconde_vie",
            field=models.BooleanField(null=True),
        ),
    ]
