# Generated by Django 4.2.13 on 2024-08-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0100_remove_programme_reassign_command_old_admin_backup"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="reassign_command_old_admin_backup",
            field=models.IntegerField(null=True),
        ),
    ]
