# Generated by Django 4.2.13 on 2024-09-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("instructeurs", "0001_initial_squashed_0017_auto_20230925_1209"),
        ("programmes", "0101_programme_reassign_command_old_admin_backup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logement",
            name="coeficient",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=12,
                null=True,
                verbose_name="Coefficient propre au logement",
            ),
        ),
        migrations.AlterField(
            model_name="logement",
            name="loyer",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="logement",
            name="loyer_par_metre_carre",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Loyer maximum en € par m² de surface utile",
            ),
        ),
        migrations.AlterField(
            model_name="logement",
            name="surface_annexes",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="logement",
            name="surface_annexes_retenue",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="logement",
            name="surface_corrigee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Surface corrigée",
            ),
        ),
        migrations.AlterField(
            model_name="logement",
            name="surface_habitable",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Surface habitable",
            ),
        ),
        migrations.AlterField(
            model_name="logement",
            name="surface_utile",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Surface utile",
            ),
        ),
        migrations.AlterField(
            model_name="logementedd",
            name="numero_lot",
            field=models.CharField(blank=True, default="", max_length=255),
            preserve_default=False,
        ),
    ]
