# Generated by Django 4.2.13 on 2024-09-03 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("instructeurs", "0001_initial_squashed_0017_auto_20230925_1209"),
        ("programmes", "0102_alter_logement_blank_and_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="edd_classique",
            field=models.TextField(blank=True, default="", max_length=50000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lot",
            name="edd_volumetrique",
            field=models.TextField(blank=True, default="", max_length=50000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lot",
            name="loyer_derogatoire",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Loyer dérogatoire",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="nb_logements",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lot",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="programmes.lot",
            ),
        ),
        migrations.AlterField(
            model_name="lot",
            name="surface_habitable_totale",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
