# Generated by Django 4.2.13 on 2024-09-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("instructeurs", "0001_initial_squashed_0017_auto_20230925_1209"),
        ("programmes", "0105_alter_ref_programme1_blank_and_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="annee_gestion_programmation",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET autres_locaux_hors_convention = '' WHERE"
            " autres_locaux_hors_convention IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="autres_locaux_hors_convention",
            field=models.TextField(blank=True),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET certificat_adressage = '' WHERE"
            " certificat_adressage IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="certificat_adressage",
            field=models.TextField(blank=True),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET code_insee_commune = '' WHERE"
            " code_insee_commune IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="code_insee_commune",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET code_insee_departement = '' WHERE"
            " code_insee_departement IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="code_insee_departement",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET code_insee_region = '' WHERE"
            " code_insee_region IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="code_insee_region",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET code_postal = '' WHERE"
            " code_postal IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="code_postal",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="programme",
            name="date_achat",
            field=models.DateField(blank=True, null=True),
        ),
    ]
