# Generated by Django 4.2.13 on 2024-09-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("instructeurs", "0001_initial_squashed_0017_auto_20230925_1209"),
        ("programmes", "0107_alter_ref_programme3_blank_and_null"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE programmes_programme SET edd_classique = '' WHERE"
            " edd_classique IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="edd_classique",
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET edd_stationnements = '' WHERE"
            " edd_stationnements IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="edd_stationnements",
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET edd_volumetrique = '' WHERE"
            " edd_volumetrique IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="edd_volumetrique",
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET effet_relatif = '' WHERE"
            " effet_relatif IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="effet_relatif",
            field=models.TextField(blank=True),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET mention_publication_edd_classique = '' WHERE"
            " mention_publication_edd_classique IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="mention_publication_edd_classique",
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET mention_publication_edd_volumetrique = ''"
            " WHERE mention_publication_edd_volumetrique IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="mention_publication_edd_volumetrique",
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name="programme",
            name="nb_bureaux",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="programme",
            name="nb_locaux_commerciaux",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
