# Generated by Django 4.2.13 on 2024-09-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("instructeurs", "0001_initial_squashed_0017_auto_20230925_1209"),
        ("programmes", "0107_alter_ref_programme3_blank_and_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="edd_classique",
            field=models.TextField(blank=True, default="", max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programme",
            name="edd_stationnements",
            field=models.TextField(blank=True, default="", max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programme",
            name="edd_volumetrique",
            field=models.TextField(blank=True, default="", max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programme",
            name="effet_relatif",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programme",
            name="mention_publication_edd_classique",
            field=models.TextField(blank=True, default="", max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programme",
            name="mention_publication_edd_volumetrique",
            field=models.TextField(blank=True, default="", max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="programme",
            name="nb_bureaux",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="programme",
            name="nb_locaux_commerciaux",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
