# Generated by Django 4.2.13 on 2024-09-03 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("instructeurs", "0001_initial_squashed_0017_auto_20230925_1209"),
        ("programmes", "0108_alter_ref_programme4_blank_and_null"),
    ]

    operations = [
        migrations.RunSQL(
            "UPDATE programmes_programme SET numero_operation = '' WHERE"
            " numero_operation IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET numero_operation_pour_recherche = '' WHERE"
            " numero_operation_pour_recherche IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="numero_operation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="programme",
            name="numero_operation_pour_recherche",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
