# Generated by Django 4.2.13 on 2024-09-03 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("instructeurs", "0001_initial_squashed_0017_auto_20230925_1209"),
        ("programmes", "0109_alter_ref_programme5_blank_and_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="programmes.programme",
            ),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET permis_construire = '' WHERE"
            " permis_construire IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="permis_construire",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="programme",
            name="reassign_command_old_admin_backup",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET reference_cadastrale = '' WHERE"
            " reference_cadastrale IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="reference_cadastrale",
            field=models.TextField(blank=True),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET reference_notaire = '' WHERE"
            " reference_notaire IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="reference_notaire",
            field=models.TextField(blank=True),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET reference_publication_acte = '' WHERE"
            " reference_publication_acte IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="reference_publication_acte",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="programme",
            name="surface_corrigee_totale",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="surface_utile_totale",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET vendeur = '' WHERE" " vendeur IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="vendeur",
            field=models.TextField(blank=True),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET ville = '' WHERE" " ville IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="ville",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunSQL(
            "UPDATE programmes_programme SET"
            " ville_signature_residence_agrement_gestionnaire_intermediation = '' WHERE"
            " ville_signature_residence_agrement_gestionnaire_intermediation IS NULL;",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="programme",
            name="ville_signature_residence_agrement_gestionnaire_intermediation",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="programme",
            name="zone_123",
            field=models.CharField(
                blank=True,
                choices=[("1", "01"), ("2", "02"), ("3", "03"), ("1bis", "1bis")],
                default=None,
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="programme",
            name="zone_abc",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A"),
                    ("Abis", "Abis"),
                    ("B1", "B1"),
                    ("B2", "B2"),
                    ("C", "C"),
                    ("DROM", "DROM"),
                ],
                default=None,
                max_length=25,
                null=True,
            ),
        ),
    ]
