# Generated by Django 5.1.1 on 2024-10-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0112_programme_prog_code_insee_reg_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="loyer_associations_foncieres",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Montant du loyer pour les associations foncières et leurs filiales",
            ),
        ),
    ]
