# Generated by Django 5.1.1 on 2024-10-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0113_logement_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="logement",
            old_name="order",
            new_name="import_order",
        ),
    ]
