# Generated by Django 5.1.3 on 2024-11-27 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0098_alter_convention_financement"),
        ("programmes", "0117_alter_lot_financement"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="convention",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lots",
                to="conventions.convention",
            ),
        ),
    ]
