# Generated by Django 5.1.3 on 2024-12-05 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0119_fill_lot_convention"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lot",
            name="convention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lots",
                to="conventions.convention",
            ),
        ),
    ]
