# Generated by Django 5.1.3 on 2025-01-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0120_lot_unique_convention_financement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogementCorrigee",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("programmes.logement",),
        ),
        migrations.CreateModel(
            name="LogementCorrigeeSansLoyer",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("programmes.logement",),
        ),
        migrations.CreateModel(
            name="LogementSansLoyer",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("programmes.logement",),
        ),
    ]
