# Generated by Django 5.1.4 on 2025-02-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0121_logementcorrigee_logementcorrigeesansloyer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencecadastrale",
            name="autre",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="referencecadastrale",
            name="numero",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
