# Generated by Django 5.1.4 on 2025-02-12 07:53

from django.db import migrations, models


def check_referencecadastrale_null_numero(apps, schema_editor):
    ReferenceCadastrale = apps.get_model("programmes", "ReferenceCadastrale")
    assert (
        ReferenceCadastrale.objects.filter(numero__isnull=True).count() == 0
    ), "Some ReferenceCadastrale have no numero"


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("programmes", "0122_alter_lot_financement"),
    ]

    operations = [
        migrations.RunPython(
            check_referencecadastrale_null_numero,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="referencecadastrale",
            name="autre",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="referencecadastrale",
            name="numero",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
