# Generated by Django 5.1.4 on 2025-02-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0122_referencecadastrale_autre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencecadastrale",
            name="autre",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="referencecadastrale",
            name="numero",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
