# Generated by Django 5.1.4 on 2025-03-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0124_alter_lot_financement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lot",
            name="programme",
        ),
    ]
