# Generated by Django 5.1.4 on 2025-03-10 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0102_remove_convention_financement"),
        ("programmes", "0125_remove_lot_programme"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lot",
            name="unique_convention_financement",
        ),
        migrations.RemoveConstraint(
            model_name="lot",
            name="unique_convention",
        ),
        migrations.AlterField(
            model_name="lot",
            name="convention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lots",
                to="conventions.convention",
            ),
        ),
        migrations.AddConstraint(
            model_name="lot",
            constraint=models.UniqueConstraint(
                fields=("convention", "financement"),
                name="unique_convention_financement",
            ),
        ),
        migrations.AddConstraint(
            model_name="lot",
            constraint=models.UniqueConstraint(
                fields=("convention",), name="unique_convention"
            ),
        ),
    ]
