# Generated by Django 5.2.3 on 2025-07-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0126_remove_lot_unique_convention_financement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typestationnement",
            name="typologie",
            field=models.CharField(
                choices=[
                    ("GARAGE_AERIEN", "Garage aérien"),
                    ("GARAGE_ENTERRE", "Garage enterré"),
                    ("PLACE_STATIONNEMENT", "Place de stationnement"),
                    ("PARKING_EXTERIEUR_PRIVATIF", "Parking extérieur privatif"),
                    ("PARKING_SOUSSOL", "Parking en sous-sol ou en superstructure"),
                    ("GARAGE_BOXE_SIMPLE", "Garage boxé simple"),
                    ("GARAGE_BOXE_DOUBLE", "Garage boxé double"),
                    ("EXTERIEUR_BOXE", "extérieur boxé"),
                    ("SOUSSOL_BOXE", "en sous-sol boxé"),
                    ("CARPORT", "Carport"),
                    ("DEUX_ROUES_EXTERIEUR", "2 roues en extérieur"),
                    ("DEUX_ROUES_SOUSSOL", "2 roues en sous-sol"),
                    ("DOUBLE_SOUSSOL", "Parking double en sous-sol"),
                    ("DOUBLE_SUPERSTRUCTURE", "Parking double en superstructure"),
                    (
                        "INDIVIDUEL_JUMELES_PAR_2",
                        "Garages individuels jumelés par blocs de 2",
                    ),
                    (
                        "PLACE_PARKING_ACCOLEE",
                        "Place de parking accolée à chaque garage",
                    ),
                    ("PARKING_SUPERSTRUCTURE", "Parking en Superstructure"),
                ],
                default="PLACE_STATIONNEMENT",
                max_length=35,
            ),
        ),
    ]
