# Generated by Django 5.2.4 on 2025-08-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0127_alter_typestationnement_typologie"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lot",
            name="unique_convention",
        ),
    ]
