# Generated by Django 5.2.4 on 2025-08-12 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructeurs", "0001_initial_squashed_0017_auto_20230925_1209"),
        ("programmes", "0127_alter_typestationnement_typologie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programme",
            name="administration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programmes",
                to="instructeurs.administration",
            ),
        ),
    ]
