# Generated by Django 5.2.6 on 2025-09-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0127_alter_typestationnement_typologie"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprogramme",
            name="anah",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="programme",
            name="anah",
            field=models.BooleanField(default=False),
        ),
    ]
