# Generated by Django 5.2.4 on 2025-10-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0128_historicalprogramme_anah_programme_anah"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="lot",
            name="unique_convention",
        ),
    ]
