# Generated by Django 5.2.4 on 2025-10-02 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0128_historicalprogramme_anah_programme_anah"),
        ("programmes", "0128_remove_lot_unique_convention"),
    ]

    operations = []
