# Generated by Django 5.2.6 on 2025-10-30 15:28

from django.db import connection, migrations


def update_edd_classique(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE programmes_programme pp
            SET edd_classique = pl.edd_classique
            FROM conventions_convention cc
            JOIN programmes_lot pl ON cc.id = pl.convention_id
            WHERE pp.id = cc.programme_id;
        """)

def update_edd_volumetrique(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute("""
            UPDATE programmes_programme pp
            SET edd_volumetrique = pl.edd_volumetrique
            FROM conventions_convention cc
            JOIN programmes_lot pl ON cc.id = pl.convention_id
            WHERE pp.id = cc.programme_id;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0128_historicalprogramme_anah_programme_anah"),
    ]

    operations = [
        migrations.RunPython(update_edd_classique),
        migrations.RunPython(update_edd_volumetrique),
    ]
