# Generated by Django 5.2.4 on 2025-11-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0129_remove_lot_unique_convention"),
        ("programmes", "0129_update_programme_edd_values"),
    ]

    operations = []
