from django.urls import path
from . import views

urlpatterns = [
    path(
        "",
        views.index,
        name="index",
    ),
    path(
        "administrations/",
        views.administrations,
        name="administrations",
    ),
    path(
        "administrations/<administration_uuid>",
        views.edit_administration,
        name="edit_administration",
    ),
    path(
        "bailleurs/",
        views.bailleurs,
        name="bailleurs",
    ),
    path(
        "bailleurs/import",
        views.CreateBulkBailleurView.as_view(),
        name="create_bulk_bailleur",
    ),
    path(
        "bailleurs/<bailleur_uuid>",
        views.edit_bailleur,
        name="edit_bailleur",
    ),
    path(
        "profile/",
        views.profile,
        name="profile",
    ),
    path(
        "users/",
        views.users,
        name="users",
    ),
    path(
        "users/<username>",
        views.edit_user,
        name="edit_user",
    ),
    path(
        "users/new/",
        views.add_user,
        name="add_user",
    ),
    path(
        "users/delete/<username>",
        views.delete_user,
        name="delete_user",
    ),
]
