# Generated by Django 3.2.5 on 2021-07-06 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conventions", "0001_initial"),
        ("programmes", "0002_auto_20210706_1816"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="programmes.lot"
            ),
        ),
        migrations.AddField(
            model_name="convention",
            name="programme",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="programmes.programme"
            ),
        ),
    ]
