# Generated by Django 3.2.5 on 2021-08-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0007_auto_20210831_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='convention',
            name='fond_propre',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='convention',
            name='numero',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
