# Generated by Django 3.2.7 on 2021-10-05 15:19

import json

from django.db import migrations


def update_fields_with_images(apps, schema_editor):

    Convention = apps.get_model("conventions", "Convention")

    for convention in Convention.objects.all():
        field = convention.comments
        if field is not None and field != "":
            try:
                json.loads(field)
            except json.decoder.JSONDecodeError:
                convention.comments = json.dumps(
                    {
                        "files": {},
                        "text": field if isinstance(field, str) else "",
                    }
                )

        convention.save()


def rollback_field_with_images(apps, schema_editor):

    Convention = apps.get_model("conventions", "Convention")

    for convention in Convention.objects.all():
        field = convention.comments
        if field is not None and field != "":
            try:
                json_field = json.loads(field)
                convention.comments = json_field["text"] if "text" in json_field else ""
            except json.decoder.JSONDecodeError:
                print(f"json error : {field}")

        convention.save()


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0010_alter_pret_preteur"),
    ]

    operations = [
        migrations.RunPython(update_fields_with_images, rollback_field_with_images),
    ]
