# Generated by Django 3.2.7 on 2021-10-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0011_auto_20211005_1719"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pret",
            name="montant",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
