# Generated by Django 3.2.8 on 2021-11-05 14:48

from django.db import migrations, models


def set_premiere_soumission_le(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    Convention = apps.get_model("conventions", "Convention")

    for convention in Convention.objects.filter(soumis_le__isnull=False):
        convention.premiere_soumission_le = convention.soumis_le
        convention.save()


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0012_alter_pret_montant"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="premiere_soumission_le",
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(set_premiere_soumission_le),
    ]
