# Generated by Django 3.2.9 on 2021-11-18 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0004_alter_bailleur_capital_social"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conventions", "0013_convention_premiere_soumission_le"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConventionHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "statut_convention",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("INSTRUCTION", "En cours d'instruction"),
                            ("CORRECTION", "Corrections requises"),
                            ("VALIDE", "Validé"),
                            ("CLOS", "Convention close"),
                        ],
                        default="BROUILLON",
                        max_length=25,
                    ),
                ),
                (
                    "statut_convention_precedent",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("INSTRUCTION", "En cours d'instruction"),
                            ("CORRECTION", "Corrections requises"),
                            ("VALIDE", "Validé"),
                            ("CLOS", "Convention close"),
                        ],
                        default="BROUILLON",
                        max_length=25,
                    ),
                ),
                ("commentaire", models.TextField(null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "bailleur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bailleurs.bailleur",
                    ),
                ),
                (
                    "convention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conventions.convention",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="valide_par",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
