# Generated by Django 3.2.9 on 2021-12-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0014_conventionhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pret",
            name="preteur",
            field=models.CharField(
                choices=[
                    ("ETAT", "Etat"),
                    ("EPCI", "EPCI"),
                    ("REGION", "Région"),
                    ("CDCF", "CDC pour le foncier"),
                    ("CDCL", "CDC pour le logement"),
                    ("COMMUNE", "Commune et action logement"),
                    ("AUTRE", "Autre"),
                ],
                default="AUTRE",
                max_length=25,
            ),
        ),
    ]
