# Generated by Django 3.2.13 on 2022-06-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0020_alter_pret_preteur"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="donnees_validees",
            field=models.TextField(null=True),
        ),
    ]
