# Generated by Django 3.2.13 on 2022-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0021_convention_donnees_validees"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="fichier_signe",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
