# Generated by Django 3.2.13 on 2022-06-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0022_convention_fichier_signe"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="date_resiliation",
            field=models.DateField(null=True),
        ),
    ]
