# Generated by Django 3.2.13 on 2022-07-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0027_auto_20220714_1216"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="financement",
            field=models.CharField(
                choices=[
                    ("PLUS", "PLUS"),
                    ("PLAI", "PLAI"),
                    ("PLAI_ADP", "PLAI_ADP"),
                    ("PLUS-PLAI", "PLUS-PLAI"),
                    ("PLS", "PLS"),
                    ("PSH", "PSH"),
                    ("PALULOS", "PALULOS"),
                    ("SANS_FINANCEMENT", "Sans Financement"),
                ],
                default="PLUS",
                max_length=25,
            ),
        ),
    ]
