# Generated by Django 3.2.13 on 2022-07-18 12:27

from django.db import migrations, models


def update_convention_status(apps, schema_editor):
    Convention = apps.get_model("conventions", "Convention")
    ConventionHistory = apps.get_model("conventions", "ConventionHistory")
    Convention.objects.filter(statut="5. Transmise").update(statut="5. Signée")

    ConventionHistory.objects.filter(statut_convention="5. Transmise").update(
        statut_convention="5. Signée"
    )

    ConventionHistory.objects.filter(statut_convention_precedent="5. Transmise").update(
        statut_convention_precedent="5. Signée"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0028_alter_convention_financement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="statut",
            field=models.CharField(
                choices=[
                    ("1. Projet", "Création d'un projet de convention"),
                    (
                        "2. Instruction requise",
                        "Projet de convention soumis à l'instruction",
                    ),
                    (
                        "3. Corrections requises",
                        "Projet de convention à modifier par le bailleur",
                    ),
                    ("4. A signer", "Convention à signer"),
                    ("5. Signée", "Convention signée"),
                    ("6. Résiliée", "Convention résiliée"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="conventionhistory",
            name="statut_convention",
            field=models.CharField(
                choices=[
                    ("1. Projet", "Création d'un projet de convention"),
                    (
                        "2. Instruction requise",
                        "Projet de convention soumis à l'instruction",
                    ),
                    (
                        "3. Corrections requises",
                        "Projet de convention à modifier par le bailleur",
                    ),
                    ("4. A signer", "Convention à signer"),
                    ("5. Signée", "Convention signée"),
                    ("6. Résiliée", "Convention résiliée"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="conventionhistory",
            name="statut_convention_precedent",
            field=models.CharField(
                choices=[
                    ("1. Projet", "Création d'un projet de convention"),
                    (
                        "2. Instruction requise",
                        "Projet de convention soumis à l'instruction",
                    ),
                    (
                        "3. Corrections requises",
                        "Projet de convention à modifier par le bailleur",
                    ),
                    ("4. A signer", "Convention à signer"),
                    ("5. Signée", "Convention signée"),
                    ("6. Résiliée", "Convention résiliée"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
        migrations.RunPython(update_convention_status),
    ]
