# Generated by Django 3.2.13 on 2022-07-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0030_auto_20220719_1436"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="avenant_type",
            field=models.CharField(
                choices=[("Logements", "Modification des logements")],
                default="Logements",
                max_length=25,
                null=True,
            ),
        ),
    ]
