# Generated by Django 3.2.14 on 2022-07-22 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0031_alter_convention_avenant_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="convention",
            old_name="parent_id",
            new_name="parent",
        ),
    ]
