# Generated by Django 3.2.14 on 2022-07-22 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0032_rename_parent_id_convention_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="avenants",
                to="conventions.convention",
            ),
        ),
    ]
