# Generated by Django 3.2.14 on 2022-10-06 03:53

from django.db import migrations, models


def assign_signataire(apps, schema_editor):

    Convention = apps.get_model("conventions", "Convention")

    for convention in Convention.objects.prefetch_related("programme__bailleur").all():
        convention.signataire_nom = convention.programme.bailleur.signataire_nom
        convention.signataire_fonction = convention.programme.bailleur.signataire_fonction
        convention.signataire_date_deliberation = (
            convention.programme.bailleur.signataire_date_deliberation
        )
        convention.save()


def nothing_to_do(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0035_convention_cree_par"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="signataire_date_deliberation",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="signataire_fonction",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="signataire_nom",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(assign_signataire, nothing_to_do),
    ]
