# Generated by Django 4.1.1 on 2022-10-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0036_auto_20221006_0553"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvenantType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255, unique=True)),
                ("desc", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="convention",
            name="avenant_type",
        ),
        migrations.AddField(
            model_name="convention",
            name="avenant_type",
            field=models.ManyToManyField(
                blank=True,
                max_length=50,
                related_name="avenant_type",
                to="conventions.avenanttype",
                verbose_name="Type d'avenant",
            ),
        ),
    ]
