# Generated by Django 4.1.1 on 2022-10-24 15:54

from django.core.management import call_command
from django.db import migrations, models

fixture = "avenant_types"


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# conventions.migrations.0038_load_avenant_type
# conventions.migrations.0039_auto_20221013_0115


def load_fixture(apps, schema_editor):
    call_command("loaddata", fixture, app_label="conventions")


def update_convention_avenanttype(apps, schema_editor):
    convention_class = apps.get_model("conventions", "Convention")
    avenant_type_class = apps.get_model("conventions", "AvenantType")
    logements = avenant_type_class.objects.get(nom="logements")
    for convention in convention_class.objects.filter(parent_id__isnull=False):
        convention.avenant_types.add(logements)


class Migration(migrations.Migration):

    replaces = [
        ("conventions", "0037_avenanttype_remove_convention_avenant_type_and_more"),
        ("conventions", "0038_load_avenant_type"),
        ("conventions", "0039_auto_20221013_0115"),
        ("conventions", "0040_remove_convention_avenant_type_and_more"),
        ("conventions", "0041_alter_convention_avenant_types"),
    ]

    dependencies = [
        ("conventions", "0036_auto_20221006_0553"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvenantType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255, unique=True)),
                ("desc", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="convention",
            name="avenant_type",
        ),
        migrations.AddField(
            model_name="convention",
            name="avenant_types",
            field=models.ManyToManyField(
                blank=True,
                max_length=50,
                related_name="avenant_types",
                to="conventions.avenanttype",
                verbose_name="Type d'avenant",
            ),
        ),
        migrations.RunPython(load_fixture, migrations.RunPython.noop),
        migrations.RunPython(update_convention_avenanttype, migrations.RunPython.noop),
    ]
