# Generated by Django 4.1.1 on 2022-10-13 00:07

from django.core.management import call_command
from django.db import migrations

fixture = "avenant_type"


def load_fixture(apps, schema_editor):
    call_command("loaddata", fixture, app_label="conventions")


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0037_avenanttype_remove_convention_avenant_type_and_more"),
    ]

    operations = [migrations.RunPython(load_fixture)]
