# Generated by Django 4.1.1 on 2022-10-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0039_auto_20221013_0115"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convention",
            name="avenant_type",
        ),
        migrations.AddField(
            model_name="convention",
            name="avenant_types",
            field=models.ManyToManyField(
                blank=True,
                max_length=50,
                to="conventions.avenanttype",
                verbose_name="Type d'avenant",
            ),
        ),
    ]
