# Generated by Django 4.1.1 on 2022-10-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0040_remove_convention_avenant_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="avenant_types",
            field=models.ManyToManyField(
                blank=True,
                max_length=50,
                related_name="avenant_types",
                to="conventions.avenanttype",
                verbose_name="Type d'avenant",
            ),
        ),
    ]
