# Generated by Django 4.1.3 on 2022-11-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0037_avenanttype_remove_convention_avenant_type_and_more_squashed_0041_alter_convention_avenant_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='bailleur',
        ),
        migrations.RemoveField(
            model_name='conventionhistory',
            name='bailleur',
        ),
        migrations.RemoveField(
            model_name='pret',
            name='bailleur',
        ),
    ]
