# Generated by Django 4.1.2 on 2022-11-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conventions', '0037_avenanttype_remove_convention_avenant_type_and_more_squashed_0041_alter_convention_avenant_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='bailleur',
        ),
    ]
