# Generated by Django 4.1.3 on 2022-12-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0044_alter_convention_lot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convention",
            name="financement",
        ),
        migrations.RemoveField(
            model_name="convention",
            name="programme",
        ),
    ]
