# Generated by Django 4.1.3 on 2022-12-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0044_alter_convention_lot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="desc_avenant",
            field=models.TextField(blank=True, null=True),
        ),
    ]
