# Generated by Django 4.1.3 on 2022-12-02 16:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0044_alter_convention_lot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PieceJointe",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CONVENTION", "Convention APL"),
                            (
                                "RECTIFICATION",
                                "Demande de rectification(s) du bureau des hypothèques",
                            ),
                            ("ATTESTATION_PREFECTORALE", "Attestations préfectorales"),
                            ("AVENANT", "Avenant"),
                            ("PHOTO", "Photographie du bâti ou des logements"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=24,
                        null=True,
                    ),
                ),
                ("fichier", models.CharField(blank=True, max_length=255, null=True)),
                ("nom_reel", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=False)),
                (
                    "convention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces_jointes",
                        to="conventions.convention",
                    ),
                ),
            ],
        ),
    ]
