# Generated by Django 4.1.3 on 2022-11-29 11:26

import compositefk.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecoloweb", "0002_alter_ecoloreference_unique_together"),
        ("conventions", "0044_alter_convention_lot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="ecolo_reference",
            field=compositefk.fields.CompositeOneToOneField(
                default=None,
                null=True,
                null_if_equal=[],
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="ecoloweb.ecoloreference",
                to_fields={
                    "apilos_id": compositefk.fields.LocalFieldValue("id"),
                    "apilos_model": compositefk.fields.RawFieldValue(
                        "conventions.Convention"
                    ),
                },
            ),
        ),
    ]
