# Generated by Django 4.1.3 on 2022-12-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0044_alter_convention_lot_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="gestionnaire",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="gestionnaire_signataire_date_deliberation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="gestionnaire_signataire_fonction",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="gestionnaire_signataire_nom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
