# Generated by Django 4.1.3 on 2022-12-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0045_create_model_pieces_jointes"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="date_envoi_spf",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="date_publication_spf",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="date_refus_spf",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="motif_refux_spf",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="reference_spf",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
