# Generated by Django 4.1.4 on 2022-12-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0048_convention_attribution_agees_autonomie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="foyer_variante_1",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="foyer_variante_2",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="foyer_variante_2_travaux",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="foyer_variante_3",
            field=models.BooleanField(default=True),
        ),
    ]
