# Generated by Django 4.1.4 on 2022-12-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0049_convention_foyer_variante_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="attached",
            field=models.TextField(blank=True, null=True),
        ),
    ]
