# Generated by Django 4.1.4 on 2022-12-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0050_convention_attached"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="historique_financement_public",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
