# Generated by Django 4.1.3 on 2022-12-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0051_convention_historique_financement_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="desc_avenant",
            field=models.TextField(blank=True, null=True),
        ),
    ]
