# Generated by Django 4.1.5 on 2023-01-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0052_convention_desc_avenant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="statut",
            field=models.CharField(
                choices=[
                    ("1. Projet", "Projet"),
                    ("2. Instruction requise", "En instruction"),
                    ("3. Corrections requises", "En correction"),
                    ("4. A signer", "À signer"),
                    ("5. Signée", "Finalisée"),
                    ("6. Résiliée", "Résiliée"),
                    ("7. Dénoncée", "Dénoncée"),
                    ("8. Annulée en suivi", "Annulée en suivi"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="conventionhistory",
            name="statut_convention",
            field=models.CharField(
                choices=[
                    ("1. Projet", "Projet"),
                    ("2. Instruction requise", "En instruction"),
                    ("3. Corrections requises", "En correction"),
                    ("4. A signer", "À signer"),
                    ("5. Signée", "Finalisée"),
                    ("6. Résiliée", "Résiliée"),
                    ("7. Dénoncée", "Dénoncée"),
                    ("8. Annulée en suivi", "Annulée en suivi"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="conventionhistory",
            name="statut_convention_precedent",
            field=models.CharField(
                choices=[
                    ("1. Projet", "Projet"),
                    ("2. Instruction requise", "En instruction"),
                    ("3. Corrections requises", "En correction"),
                    ("4. A signer", "À signer"),
                    ("5. Signée", "Finalisée"),
                    ("6. Résiliée", "Résiliée"),
                    ("7. Dénoncée", "Dénoncée"),
                    ("8. Annulée en suivi", "Annulée en suivi"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
    ]
