# Generated by Django 4.1.5 on 2023-01-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0053_alter_convention_statut_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piecejointe",
            name="description",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="piecejointe",
            name="fichier",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
