# Generated by Django 4.1.5 on 2023-01-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0053_alter_convention_statut_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="attribution_pension_de_famille",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="convention",
            name="attribution_residence_accueil",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="convention",
            name="attribution_residence_sociale_ordinaire",
            field=models.BooleanField(default=False),
        ),
    ]
