# Generated by Django 4.1.5 on 2023-01-30 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0054_convention_attribution_pension_de_famille_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="convention",
            old_name="foyer_variante_1",
            new_name="foyer_residence_variante_1",
        ),
        migrations.RenameField(
            model_name="convention",
            old_name="foyer_variante_2",
            new_name="foyer_residence_variante_2",
        ),
        migrations.RenameField(
            model_name="convention",
            old_name="foyer_variante_2_travaux",
            new_name="foyer_residence_variante_2_travaux",
        ),
        migrations.RenameField(
            model_name="convention",
            old_name="foyer_variante_3",
            new_name="foyer_residence_variante_3",
        ),
    ]
