# Generated by Django 4.1.5 on 2023-01-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "conventions",
            "0055_rename_foyer_variante_1_convention_foyer_residence_variante_1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="foyer_residence_variante_2_nb_annees",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="foyer_residence_variante_2_nb_tranches",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
