# Generated by Django 4.1.5 on 2023-01-31 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "conventions",
            "0056_convention_foyer_residence_variante_2_nb_annees_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="convention",
            old_name="attribution_reservation_prefectoral",
            new_name="attribution_reservation_prefectorale",
        ),
    ]
