# Generated by Django 4.1.5 on 2023-02-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0059_rename_comments_convention_commentaires"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="gestionnaire_signataire_bloc_signature",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="signataire_bloc_signature",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name="convention",
            name="signataire_date_deliberation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="convention",
            name="signataire_fonction",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="convention",
            name="signataire_nom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
