# Generated by Django 4.1.7 on 2023-03-17 10:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "conventions",
            "0060_convention_gestionnaire_signataire_bloc_signature_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Evenement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "type_evenement",
                    models.CharField(
                        choices=[
                            (
                                "DEPOT_BAILLEUR",
                                "Dépôt de la convention APL par le bailleur",
                            ),
                            (
                                "MODIFICATION",
                                "Modification de la convention (valeur du loyer plafond, surface, clauses, etc...)",
                            ),
                            (
                                "ECHANGE",
                                "Echanges téléphoniques, électroniques ou transmission par courrier de la convention APL au bailleur",
                            ),
                            (
                                "ENVOI_PREFET",
                                "Transmission de la convention APL à la signature du préfet",
                            ),
                            (
                                "RETOUR_PREFET",
                                "Retour de la convention APL signée par le préfet",
                            ),
                            (
                                "ENVOI_HYPOTHEQUE",
                                "Transmission de la convention APL au bureau des hypothèques ou au livre foncier",
                            ),
                            (
                                "RETOUR_HYPOTHEQUE",
                                "Retour du bureau des hypothèques ou au livre foncier, pour modification",
                            ),
                            (
                                "ENVOI_RECTIFICATIF_PREFET",
                                "Transmission de l'attestation rectificative à la signature du préfet",
                            ),
                            (
                                "RETOUR_RECTIFICATIF_PREFET",
                                "Retour de l'attestation préfectorale de la convention APL",
                            ),
                            (
                                "PUBLICATION_HYPOTHEQUE",
                                "Publication de la convention APL au bureau des hypothèques",
                            ),
                            ("ENVOI_CAF", "Transmission de la convention APL à la CAF"),
                            ("DEPOT_AVENANT", "Dépôt d'un avenant par le bailleur"),
                            (
                                "INSTRUCTION_AVENANT",
                                "Instruction d'un avenant, objet de l'avenant, etc...",
                            ),
                            (
                                "CORRECTION_AVENANT",
                                "Modification de l'avenant sur demande de l'instructeur auprès du bailleur",
                            ),
                            (
                                "ENVOI_AVENANT_PREFET",
                                "Transmission de l'avenant à la signature du préfet",
                            ),
                            (
                                "SIGNATURE_AVENANT_PREFET",
                                "Retour de l'avenant signé par le préfet",
                            ),
                            (
                                "ENVOI_AVENANT_HYPOTHEQUE",
                                "Transmission de l'avenant au bureau des hypothèques ou au livre foncier",
                            ),
                            (
                                "RETOUR_AVENANT_HYPOTHEQUE",
                                "Retour de l'avenant du bureau des hypothèques ou du livre foncier, pour modification",
                            ),
                            (
                                "ENVOI_RECTIFICATIF_AVENANT_PREFET",
                                "Transmission de l'attestation rectificative d'avenant à la signature du préfet",
                            ),
                            (
                                "RETOUR_RECTIFICATIF_AVENANT_PREFET",
                                "Retour de l'attestation préfectorale de l'avenant",
                            ),
                            (
                                "PUBLICATION_AVENANT_HYPOTHEQUE",
                                "Publication de l'avenant de la convention APL au bureau des hypothèques",
                            ),
                            (
                                "EXPIRATION_CONVENTION",
                                "Expiration de la convention APL",
                            ),
                            (
                                "ENVOI_FIN_DENONCIATION",
                                "Information auprès du bailleur de la date butoir de dénonciation de la convention APL",
                            ),
                            ("AUTRE", "Autres"),
                        ],
                        default="DEPOT_BAILLEUR",
                        max_length=50,
                    ),
                ),
                ("survenu_le", models.DateField(editable=False)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "convention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evenements",
                        to="conventions.convention",
                    ),
                ),
            ],
        ),
    ]
