# Generated by Django 4.1.7 on 2023-04-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0061_evenement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="statut",
            field=models.CharField(
                choices=[
                    ("PROJET", "1. Projet"),
                    ("INSTRUCTION", "2. Instruction requise"),
                    ("CORRECTION", "3. Corrections requises"),
                    ("A_SIGNER", "4. A signer"),
                    ("SIGNEE", "5. Signée"),
                    ("RESILIEE", "6. Résiliée"),
                    ("DENONCEE", "7. Dénoncée"),
                    ("ANNULEE", "8. Annulée en suivi"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="conventionhistory",
            name="statut_convention",
            field=models.CharField(
                choices=[
                    ("PROJET", "1. Projet"),
                    ("INSTRUCTION", "2. Instruction requise"),
                    ("CORRECTION", "3. Corrections requises"),
                    ("A_SIGNER", "4. A signer"),
                    ("SIGNEE", "5. Signée"),
                    ("RESILIEE", "6. Résiliée"),
                    ("DENONCEE", "7. Dénoncée"),
                    ("ANNULEE", "8. Annulée en suivi"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="conventionhistory",
            name="statut_convention_precedent",
            field=models.CharField(
                choices=[
                    ("PROJET", "1. Projet"),
                    ("INSTRUCTION", "2. Instruction requise"),
                    ("CORRECTION", "3. Corrections requises"),
                    ("A_SIGNER", "4. A signer"),
                    ("SIGNEE", "5. Signée"),
                    ("RESILIEE", "6. Résiliée"),
                    ("DENONCEE", "7. Dénoncée"),
                    ("ANNULEE", "8. Annulée en suivi"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
    ]
