# Generated by Django 4.1.7 on 2023-04-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0062_alter_convention_statut_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenement",
            name="type_evenement",
            field=models.CharField(
                choices=[
                    ("DEPOT_BAILLEUR", "Dépôt de la convention APL parle bailleur"),
                    (
                        "MODIFICATION",
                        "Modification de la convention (valeur du loyer plafond, surface,clauses, etc...)",
                    ),
                    (
                        "ECHANGE",
                        "Echanges téléphoniques, électroniques ou transmission par courrierde la convention APL au bailleur",
                    ),
                    (
                        "ENVOI_PREFET",
                        "Transmission de la convention APL à la signature du préfet",
                    ),
                    (
                        "RETOUR_PREFET",
                        "Retour de la convention APL signée parle préfet",
                    ),
                    (
                        "ENVOI_HYPOTHEQUE",
                        "Transmission de la convention APL au bureau des hypothèques ou aulivre foncier",
                    ),
                    (
                        "RETOUR_HYPOTHEQUE",
                        "Retour du bureau des hypothèques ou au livre foncier, pourmodification",
                    ),
                    (
                        "ENVOI_RECTIFICATIF_PREFET",
                        "Transmission de l'attestation rectificative à la signature du préfet",
                    ),
                    (
                        "RETOUR_RECTIFICATIF_PREFET",
                        "Retour de l'attestation préfectorale de la convention APL",
                    ),
                    (
                        "PUBLICATION_HYPOTHEQUE",
                        "Publication de la convention APL au bureau des hypothèques",
                    ),
                    ("ENVOI_CAF", "Transmission de la convention APL à la CAF"),
                    ("DEPOT_AVENANT", "Dépôt d'un avenant par le bailleur"),
                    (
                        "INSTRUCTION_AVENANT",
                        "Instruction d'un avenant, objet de l'avenant, etc...",
                    ),
                    (
                        "CORRECTION_AVENANT",
                        "Modification de l'avenant sur demande de l'instructeur auprès dubailleur",
                    ),
                    (
                        "ENVOI_AVENANT_PREFET",
                        "Transmission de l'avenant à la signature du préfet",
                    ),
                    (
                        "SIGNATURE_AVENANT_PREFET",
                        "Retour de l'avenant signé par le préfet",
                    ),
                    (
                        "ENVOI_AVENANT_HYPOTHEQUE",
                        "Transmission de l'avenant au bureau des hypothèques ou au livrefoncier",
                    ),
                    (
                        "RETOUR_AVENANT_HYPOTHEQUE",
                        "Retour de l'avenant du bureau des hypothèques ou du livre foncier,pour modification",
                    ),
                    (
                        "ENVOI_RECTIFICATIF_AVENANT_PREFET",
                        "Transmission de l'attestation rectificative d'avenant à la signaturedu préfet",
                    ),
                    (
                        "RETOUR_RECTIFICATIF_AVENANT_PREFET",
                        "Retour de l'attestation préfectorale de l'avenant",
                    ),
                    (
                        "PUBLICATION_AVENANT_HYPOTHEQUE",
                        "Publication de l'avenant de la convention APL au bureau deshypothèques",
                    ),
                    ("EXPIRATION_CONVENTION", "Expiration de laconvention APL"),
                    (
                        "ENVOI_FIN_DENONCIATION",
                        "Information auprès du bailleur de la date butoir de dénonciation dela convention APL",
                    ),
                    ("AUTRE", "Autres"),
                ],
                default="DEPOT_BAILLEUR",
                max_length=50,
            ),
        ),
    ]
