# Generated by Django 4.2.1 on 2023-05-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0063_alter_evenement_type_evenement"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="convention",
            index=models.Index(fields=["statut"], name="conventions_statut_565eb6_idx"),
        ),
    ]
