# Generated by Django 4.2.1 on 2023-05-26 10:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0063_alter_evenement_type_evenement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name="convention",
            index=models.Index(fields=["uuid"], name="convention_uuid_idx"),
        ),
        migrations.AddIndex(
            model_name="convention",
            index=models.Index(fields=["numero"], name="convention_numero_idx"),
        ),
        migrations.AddIndex(
            model_name="convention",
            index=models.Index(fields=["valide_le"], name="convention_valid_le_idx"),
        ),
    ]
