# Generated by Django 4.2.1 on 2023-05-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "conventions",
            "0064_alter_convention_uuid_convention_convention_uuid_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="convention",
            index=models.Index(fields=["statut"], name="convention_statut_idx"),
        ),
    ]
