# Generated by Django 4.2.1 on 2023-06-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0066_alter_evenement_type_evenement"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="convention",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "statut__in",
                        [
                            "1. Projet",
                            "2. Instruction requise",
                            "3. Corrections requises",
                            "4. A signer",
                            "5. Signée",
                        ],
                    )
                ),
                fields=("programme_id", "lot_id", "financement"),
                name="unique_display_name",
            ),
        ),
    ]
