# Generated by Django 4.2.3 on 2023-07-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0067_convention_unique_display_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="convention",
            name="unique_display_name",
        ),
        migrations.AlterField(
            model_name="convention",
            name="statut",
            field=models.CharField(
                choices=[
                    ("PROJET", "1. Projet"),
                    ("INSTRUCTION", "2. Instruction requise"),
                    ("CORRECTION", "3. Corrections requises"),
                    ("A_SIGNER", "4. À signer"),
                    ("SIGNEE", "5. Signée"),
                    ("RESILIEE", "6. Résiliée"),
                    ("DENONCEE", "7. Dénoncée"),
                    ("ANNULEE", "8. Annulée en suivi"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="conventionhistory",
            name="statut_convention",
            field=models.CharField(
                choices=[
                    ("PROJET", "1. Projet"),
                    ("INSTRUCTION", "2. Instruction requise"),
                    ("CORRECTION", "3. Corrections requises"),
                    ("A_SIGNER", "4. À signer"),
                    ("SIGNEE", "5. Signée"),
                    ("RESILIEE", "6. Résiliée"),
                    ("DENONCEE", "7. Dénoncée"),
                    ("ANNULEE", "8. Annulée en suivi"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="conventionhistory",
            name="statut_convention_precedent",
            field=models.CharField(
                choices=[
                    ("PROJET", "1. Projet"),
                    ("INSTRUCTION", "2. Instruction requise"),
                    ("CORRECTION", "3. Corrections requises"),
                    ("A_SIGNER", "4. À signer"),
                    ("SIGNEE", "5. Signée"),
                    ("RESILIEE", "6. Résiliée"),
                    ("DENONCEE", "7. Dénoncée"),
                    ("ANNULEE", "8. Annulée en suivi"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
        migrations.AddConstraint(
            model_name="convention",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "statut__in",
                        [
                            "1. Projet",
                            "2. Instruction requise",
                            "3. Corrections requises",
                            "4. À signer",
                            "5. Signée",
                        ],
                    )
                ),
                fields=("programme_id", "lot_id", "financement"),
                name="unique_display_name",
            ),
        ),
    ]
