# Generated by Django 4.2.1 on 2023-07-07 15:38

from django.db import migrations


def add_avenant_types(apps, schema_editor):
    AvenantType = apps.get_model("conventions", "AvenantType")
    AvenantType.objects.create(
        nom="programme",
        desc="Suite à la modification du nom ou de l'adresse de l'opération",
    )
    AvenantType.objects.create(
        nom="champ_libre",
        desc="Pour ajouter, dans l'avenant, des renseignements supplémentaires de type désignation des immeubles, origines des propriétés ou autre.",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0068_convention_champ_libre_avenant"),
    ]

    operations = [
        migrations.RunPython(add_avenant_types),
    ]
