# Generated by Django 4.2.3 on 2023-09-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0070_auto_20230725_1842"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="date_denonciation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="fichier_instruction_denonciation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="motif_denonciation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
