# Generated by Django 4.2.5 on 2023-10-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0071_convention_date_denonciation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="avenant_types",
            field=models.ManyToManyField(
                blank=True,
                max_length=50,
                related_name="conventions",
                to="conventions.avenanttype",
                verbose_name="Type d'avenant",
            ),
        ),
    ]
