# Generated by Django 4.2.5 on 2023-10-15 17:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0071_convention_date_denonciation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="convention",
            old_name="commentaires",
            new_name="commentaires_text",
        ),
    ]
