# Generated by Django 4.2.5 on 2023-10-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0071_convention_date_denonciation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="televersement_convention_signee_le",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="convention",
            name="valide_le",
            field=models.DateField(blank=True, null=True),
        ),
    ]
