# Generated by Django 4.2.5 on 2023-11-03 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "conventions",
            "0072_alter_convention_televersement_convention_signee_le_and_more",
        ),
        ("conventions", "0072_rename_commentaires_convention_commentaires_text"),
    ]

    operations = []
