# Generated by Django 4.2.7 on 2023-12-21 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0074_convention_adresse_convention_code_postal_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convention",
            name="code_postal",
        ),
        migrations.RemoveField(
            model_name="convention",
            name="ville",
        ),
    ]
