# Generated by Django 4.2.7 on 2023-12-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0075_remove_convention_code_postal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="avenant_types",
            field=models.ManyToManyField(
                blank=True,
                max_length=50,
                related_name="conventions",
                to="conventions.avenanttype",
                verbose_name="Type d'avenant",
            ),
        ),
        migrations.AddIndex(
            model_name="avenanttype",
            index=models.Index(fields=["nom"], name="avenant_type_nom_idx"),
        ),
    ]
