# Generated by Django 4.2.7 on 2024-01-15 15:12

from django.db import migrations


def add_avenant_types(apps, schema_editor):
    AvenantType = apps.get_model("conventions", "AvenantType")
    AvenantType.objects.create(
        nom="resiliation",
        desc="Résilier une convention et ses avenants.",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0076_alter_convention_avenant_types_and_more"),
    ]

    operations = [
        migrations.RunPython(add_avenant_types),
    ]
