# Generated by Django 4.2.7 on 2024-01-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0077_auto_20240115_1612"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="fichier_instruction_resiliation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="motif_resiliation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
