# Generated by Django 4.2.7 on 2024-01-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0078_convention_fichier_instruction_resiliation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="date_resiliation_definitive",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="convention",
            name="date_resiliation_demandee",
            field=models.DateField(blank=True, null=True),
        ),
    ]
