# Generated by Django 4.2.9 on 2024-01-30 09:18

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("conventions", "0079_convention_fichier_instruction_resiliation_and_more"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="convention",
            index=models.Index(
                fields=["televersement_convention_signee_le"],
                name="convention_tele_signee_le_idx",
            ),
        ),
    ]
