# Generated by Django 4.2.10 on 2024-03-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0081_convention_gestionnaire_bloc_info_complementaire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="attribution_inclusif_activites",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name="convention",
            name="attribution_inclusif_conditions_admission",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name="convention",
            name="attribution_inclusif_conditions_specifiques",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name="convention",
            name="attribution_inclusif_modalites_attribution",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name="convention",
            name="attribution_inclusif_partenariats",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name="convention",
            name="attribution_modalites_choix_personnes",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name="convention",
            name="attribution_modalites_reservations",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name="convention",
            name="attribution_prestations_facultatives",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name="convention",
            name="attribution_prestations_integrees",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
