# Generated by Django 4.2.10 on 2024-04-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "conventions",
            "0082_alter_convention_attribution_inclusif_activites_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="fichier_override_cerfa",
            field=models.TextField(blank=True, null=True),
        ),
    ]
