# Generated by Django 4.2.13 on 2024-06-03 15:17

from django.db import migrations, models


def set_numero_op_for_search(apps, schema_editor):
    Convention = apps.get_model("conventions", "Convention")
    for c in Convention.objects.exclude(numero__isnull=True):
        c.numero_pour_recherche = (
            c.numero.replace("/", "").replace("-", "").replace(" ", "")
        )
        c.save()


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0084_alter_convention_financement"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="numero_pour_recherche",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="convention",
            index=models.Index(
                fields=["numero_pour_recherche"], name="convention_num_for_search_idx"
            ),
        ),
        migrations.RunPython(set_numero_op_for_search, migrations.RunPython.noop),
    ]
