# Generated by Django 4.2.13 on 2024-06-03 15:17

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0084_alter_convention_financement"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="numero_pour_recherche",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="convention",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["numero_pour_recherche"], name="convention_num_for_search_idx"
            ),
        ),
    ]
