# Generated by Django 4.2.13 on 2024-06-03 17:17

from django.db import migrations


def set_numero_op_for_search(apps, schema_editor):
    Convention = apps.get_model("conventions", "Convention")
    conventions = (
        Convention.objects.exclude(numero__isnull=True)
        .exclude(numero="")
        .order_by("id")
    )
    i = 0
    while convs := conventions[i : i + 1000]:
        for c in convs:
            c.numero_pour_recherche = (
                c.numero.replace("/", "")
                .replace("-", "")
                .replace(" ", "")
                .replace(".", "")
            )
            c.save()
        i += 1000


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("conventions", "0085_convention_numero_pour_recherche_1"),
    ]

    operations = [
        migrations.RunPython(set_numero_op_for_search, migrations.RunPython.noop),
    ]
