# Generated by Django 4.2.13 on 2024-07-03 15:53

from django.db import migrations
from django.db.models import F, Q


def check_convention_lot_financement(apps, schema_editor):
    Convention = apps.get_model("conventions", "Convention")

    qs = Convention.objects.annotate(lot_financement=F("lot__financement")).filter(
        ~Q(financement=F("lot_financement"))
    )

    assert qs.count() == 0, list(qs.values_list("id", "financement", "lot_financement"))


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0086_alter_convention_financement"),
    ]

    operations = [
        migrations.RunPython(
            check_convention_lot_financement,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="convention",
            name="financement",
        ),
    ]
