# Generated by Django 4.2.13 on 2024-07-03 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0097_alter_lot_financement"),
        ("conventions", "0089_alter_convention_financement"),
    ]

    operations = [
        migrations.AddField(
            model_name="pret",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prets",
                to="programmes.lot",
            ),
        ),
    ]
