# Generated by Django 4.2.13 on 2024-07-03 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programmes", "0097_alter_lot_financement"),
        ("conventions", "0091_migrate_prets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pret",
            name="convention",
        ),
        migrations.AlterField(
            model_name="pret",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prets",
                to="programmes.lot",
            ),
        ),
    ]
