# Generated by Django 4.2.13 on 2024-09-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0092_remove_pret_convention_alter_pret_lot"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="piece_jointe",
            field=models.TextField(blank=True),
        ),
    ]
