# Generated by Django 4.2.15 on 2024-09-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0092_remove_pret_convention_alter_pret_lot"),
    ]

    operations = [
        migrations.AddField(
            model_name="evenement",
            name="pieces_jointes",
            field=models.TextField(blank=True),
        ),
    ]
