# Generated by Django 4.2.13 on 2024-09-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0093_evenement_pieces_jointes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="convention",
            index=models.Index(fields=["cree_le"], name="convention_cree_le_idx"),
        ),
    ]
