# Generated by Django 5.1.1 on 2024-11-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0094_convention_convention_cree_le_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="identification_bailleur",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="convention",
            name="identification_bailleur_detail",
            field=models.TextField(blank=True, null=True),
        ),
    ]
