# Generated by Django 5.1.1 on 2024-10-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0095_convention_signataire_personalise_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="convention",
            old_name="signataire_personalise",
            new_name="identification_bailleur",
        ),
        migrations.RenameField(
            model_name="convention",
            old_name="signataire_personalise_detail",
            new_name="identification_bailleur_detail",
        ),
    ]
