# Generated by Django 5.1.3 on 2024-12-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0098_alter_convention_financement"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="convention",
            name="unique_display_name",
        ),
        migrations.RemoveField(
            model_name="convention",
            name="lot",
        ),
    ]
