# Generated by Django 5.1.3 on 2024-12-05 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0098_alter_convention_financement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convention",
            name="lot",
        ),
    ]
