# Generated by Django 5.1.2 on 2024-12-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0098_alter_convention_financement"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="test_field",
            field=models.CharField(blank=True, null=True),
        ),
    ]
