# Generated by Django 5.1.3 on 2024-12-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0099_remove_convention_lot"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="convention",
            name="unique_display_name",
        ),
    ]
