# Generated by Django 5.1.3 on 2024-12-13 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conventions", "0099_remove_convention_unique_display_name_and_more"),
    ]

    operations = [
        # TODO : migration pour cloner les lots quand ils ont plusieurs conventions
        # migrations.RunPython()
    ]
