# Generated by Django 5.1.7 on 2025-05-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0102_remove_convention_financement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="date_envoi_spf",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="convention",
            name="date_publication_spf",
            field=models.DateField(blank=True, null=True),
        ),
    ]
