# Generated by Django 5.2.3 on 2025-07-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0103_alter_convention_date_envoi_spf_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convention",
            name="statut",
            field=models.CharField(
                choices=[
                    ("PROJET", "1. Projet"),
                    ("INSTRUCTION", "2. Instruction requise"),
                    ("CORRECTION", "3. Corrections requises"),
                    ("A_SIGNER", "4. A signer"),
                    ("SIGNEE", "5. Signée"),
                    ("PUBLICATION", "5. En cours de publication"),
                    ("RESILIEE", "6. Résiliée"),
                    ("DENONCEE", "7. Dénoncée"),
                    ("ANNULEE", "8. Annulée en suivi"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="conventionhistory",
            name="statut_convention",
            field=models.CharField(
                choices=[
                    ("PROJET", "1. Projet"),
                    ("INSTRUCTION", "2. Instruction requise"),
                    ("CORRECTION", "3. Corrections requises"),
                    ("A_SIGNER", "4. A signer"),
                    ("SIGNEE", "5. Signée"),
                    ("PUBLICATION", "5. En cours de publication"),
                    ("RESILIEE", "6. Résiliée"),
                    ("DENONCEE", "7. Dénoncée"),
                    ("ANNULEE", "8. Annulée en suivi"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="conventionhistory",
            name="statut_convention_precedent",
            field=models.CharField(
                choices=[
                    ("PROJET", "1. Projet"),
                    ("INSTRUCTION", "2. Instruction requise"),
                    ("CORRECTION", "3. Corrections requises"),
                    ("A_SIGNER", "4. A signer"),
                    ("SIGNEE", "5. Signée"),
                    ("PUBLICATION", "5. En cours de publication"),
                    ("RESILIEE", "6. Résiliée"),
                    ("DENONCEE", "7. Dénoncée"),
                    ("ANNULEE", "8. Annulée en suivi"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
    ]
