# Generated by Django 5.2.4 on 2025-07-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0103_alter_convention_date_envoi_spf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="nom_fichier_publication_spf",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="convention",
            name="statut",
            field=models.CharField(
                choices=[
                    ("PROJET", "1. Projet"),
                    ("INSTRUCTION", "2. Instruction requise"),
                    ("CORRECTION", "3. Corrections requises"),
                    ("A_SIGNER", "4. A signer"),
                    ("SIGNEE", "5. Signée"),
                    ("PUBLICATION_EN_COURS", "5. Publication en cours"),
                    ("PUBLIE", "7. Publié"),
                    ("RESILIEE", "6. Résiliée"),
                    ("DENONCEE", "7. Dénoncée"),
                    ("ANNULEE", "8. Annulée en suivi"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="conventionhistory",
            name="statut_convention",
            field=models.CharField(
                choices=[
                    ("PROJET", "1. Projet"),
                    ("INSTRUCTION", "2. Instruction requise"),
                    ("CORRECTION", "3. Corrections requises"),
                    ("A_SIGNER", "4. A signer"),
                    ("SIGNEE", "5. Signée"),
                    ("PUBLICATION_EN_COURS", "5. Publication en cours"),
                    ("PUBLIE", "7. Publié"),
                    ("RESILIEE", "6. Résiliée"),
                    ("DENONCEE", "7. Dénoncée"),
                    ("ANNULEE", "8. Annulée en suivi"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="conventionhistory",
            name="statut_convention_precedent",
            field=models.CharField(
                choices=[
                    ("PROJET", "1. Projet"),
                    ("INSTRUCTION", "2. Instruction requise"),
                    ("CORRECTION", "3. Corrections requises"),
                    ("A_SIGNER", "4. A signer"),
                    ("SIGNEE", "5. Signée"),
                    ("PUBLICATION_EN_COURS", "5. Publication en cours"),
                    ("PUBLIE", "7. Publié"),
                    ("RESILIEE", "6. Résiliée"),
                    ("DENONCEE", "7. Dénoncée"),
                    ("ANNULEE", "8. Annulée en suivi"),
                ],
                default="1. Projet",
                max_length=25,
            ),
        ),
    ]
