# Generated by Django 5.2.3 on 2025-07-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0104_convention_televersement_publication_acte_le_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="nom_fichier_bordereau_publication",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
