# Generated by Django 5.2.4 on 2026-01-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0104_convention_nom_fichier_publication_spf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="parents",
            field=models.ManyToManyField(
                blank=True,
                related_name="seconde_vie_children",
                to="conventions.convention",
            ),
        ),
    ]
