# Generated by Django 5.2.4 on 2025-08-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0104_convention_nom_fichier_publication_spf_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="type_convention",
            field=models.CharField(
                choices=[("simple", "Simple"), ("mixte", "Mixte")],
                default="simple",
                max_length=10,
            ),
        ),
    ]
