# Generated by Django 5.2.4 on 2025-08-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0105_convention_type_convention"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convention",
            name="type_convention",
        ),
    ]
