# Generated by Django 5.2.4 on 2026-06-08 12:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0105_convention_parents"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlerteSIAPLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("CREATION", "Création"),
                            ("SUPPRESSION", "Suppression"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("ENVOYEE", "Envoyée"), ("ECHEC", "Échec")],
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("destinataires", models.JSONField(blank=True, default=list)),
                ("etiquette", models.CharField(blank=True, default="", max_length=255)),
                (
                    "user_login",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "habilitation_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("erreur", models.TextField(blank=True, default="")),
                ("payload", models.JSONField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "convention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerte_siap_logs",
                        to="conventions.convention",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log alerte SIAP",
                "verbose_name_plural": "Logs alertes SIAP",
                "ordering": ["-cree_le"],
            },
        ),
    ]
