# Generated by Django 5.2.4 on 2025-07-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0105_convention_nom_fichier_bordereau_publication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="convention",
            name="televersement_publication_acte_le",
        ),
    ]
