# Generated by Django 5.2.4 on 2025-07-22 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0106_remove_convention_televersement_publication_acte_le"),
    ]

    operations = [
        migrations.RenameField(
            model_name="convention",
            old_name="nom_fichier_bordereau_publication",
            new_name="nom_fichier_publication_spf",
        ),
    ]
