# Generated by Django 4.2.11 on 2024-04-17 12:51

import uuid

import django.db.models.deletion
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("bailleurs", "0001_initial"),
        ("bailleurs", "0002_auto_20210723_1158"),
        ("bailleurs", "0003_alter_bailleur_options"),
        ("bailleurs", "0004_alter_bailleur_capital_social"),
        ("bailleurs", "0005_auto_20211201_1558"),
        ("bailleurs", "0006_bailleur_type_bailleur"),
        ("bailleurs", "0007_auto_20220119_1059"),
        ("bailleurs", "0008_alter_bailleur_type_bailleur"),
        ("bailleurs", "0009_alter_bailleur_siret"),
        ("bailleurs", "0010_bailleur_siren"),
        ("bailleurs", "0011_bailleur_parent"),
        ("bailleurs", "0012_rename_type_bailleur_bailleur_sous_nature_bailleur"),
        ("bailleurs", "0013_bailleur_nature_bailleur"),
        ("bailleurs", "0014_alter_bailleur_capital_social_and_more"),
        ("bailleurs", "0015_alter_bailleur_sous_nature_bailleur"),
        ("bailleurs", "0016_alter_bailleur_siret"),
        (
            "bailleurs",
            "0017_alter_bailleur_adresse_alter_bailleur_code_postal_and_more",
        ),
        ("bailleurs", "0018_bailleur_signataire_bloc_signature"),
        ("bailleurs", "0019_auto_20230314_1019"),
        ("bailleurs", "0020_historicalbailleur"),
        ("bailleurs", "0021_remove_historicalbailleur_history_user_and_more"),
        ("bailleurs", "0022_auto_20230410_1530"),
        ("bailleurs", "0023_alter_bailleur_siren_alter_bailleur_uuid_and_more"),
        ("bailleurs", "0024_bailleur_search_vector_and_more"),
        ("bailleurs", "0025_search_vector_trigger"),
        ("bailleurs", "0026_remove_bailleur_search_vector_bailleur_idx_and_more"),
        ("bailleurs", "0027_remove_search_vector_trigger"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bailleur",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("nom", models.CharField(max_length=255)),
                ("siret", models.CharField(max_length=255, unique=True)),
                (
                    "signataire_nom",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "signataire_fonction",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "signataire_date_deliberation",
                    models.DateField(blank=True, null=True),
                ),
                ("operation_exceptionnelle", models.TextField(blank=True, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("mis_a_jour_le", models.DateTimeField(auto_now=True)),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                ("code_postal", models.CharField(blank=True, max_length=5, null=True)),
                ("ville", models.CharField(blank=True, max_length=255, null=True)),
                ("capital_social", models.FloatField(blank=True, null=True)),
                (
                    "sous_nature_bailleur",
                    models.CharField(
                        choices=[
                            ("ASSOCIATIONS", "Associations"),
                            ("ANAH", "ANAH"),
                            ("COMMERCIALES", "entreprises commerciales"),
                            ("COMMUNE", "Commune"),
                            ("COOPERATIVE_HLM_SCIC", "Sté coopérative HLM /SCIC"),
                            ("CROUS", "CROUS"),
                            ("DEPARTEMENT", "Département"),
                            ("DRE_DDE_CETE_AC_PREF", "DRE,DDE,CETE,AC,Préfect."),
                            ("EPCI", "EPCI"),
                            ("ETC_PUBLIQUE_LOCAL", "Ets public local"),
                            ("ETS_HOSTIPATIERS_PRIVES", "Ets hospitaliers privés"),
                            ("FONDATION", "Fondation"),
                            ("FONDATION_HLM", "Fondation HLM"),
                            ("FRONCIERE_LOGEMENT", "Foncière Logement"),
                            ("GIP", "GIP"),
                            ("MUTUELLE", "Mutuelle"),
                            ("NONRENSEIGNE", "Non renseigné"),
                            ("OFFICE_PUBLIC_HLM", "Office public HLM (OPH)"),
                            ("PACT_ARIM", "Pact-Arim"),
                            ("PARTICULIERS", "Particuliers"),
                            ("SA_HLM_ESH", "SA HLM / ESH"),
                            ("SACI_CAP", "SACI CAP"),
                            ("SEM_EPL", "SEM / EPL"),
                            ("UES", "UES"),
                        ],
                        default="NONRENSEIGNE",
                        max_length=25,
                    ),
                ),
                ("siren", models.CharField(max_length=255, null=True, unique=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bailleurs",
                        to="bailleurs.bailleur",
                    ),
                ),
                (
                    "nature_bailleur",
                    models.CharField(
                        choices=[
                            (
                                "Autres bailleurs sociaux non HLM",
                                "Autres bailleurs sociaux non HLM",
                            ),
                            ("Bailleurs privés", "Bailleurs privés"),
                            ("HLM", "HLM"),
                            ("SEM", "SEM"),
                        ],
                        default="Autres bailleurs sociaux non HLM",
                        max_length=255,
                    ),
                ),
                (
                    "signataire_bloc_signature",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalBailleur",
            fields=[
                ("id", models.IntegerField(blank=True, db_index=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("nom", models.CharField(max_length=255)),
                ("siret", models.CharField(db_index=True, max_length=255)),
                ("siren", models.CharField(db_index=True, max_length=255, null=True)),
                ("capital_social", models.FloatField(blank=True, null=True)),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                ("code_postal", models.CharField(blank=True, max_length=5, null=True)),
                ("ville", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "signataire_nom",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "signataire_fonction",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "signataire_date_deliberation",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "signataire_bloc_signature",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                ("operation_exceptionnelle", models.TextField(blank=True, null=True)),
                (
                    "nature_bailleur",
                    models.CharField(
                        choices=[
                            (
                                "Autres bailleurs sociaux non HLM",
                                "Autres bailleurs sociaux non HLM",
                            ),
                            ("Bailleurs privés", "Bailleurs privés"),
                            ("HLM", "HLM"),
                            ("SEM", "SEM"),
                        ],
                        default="Autres bailleurs sociaux non HLM",
                        max_length=255,
                    ),
                ),
                (
                    "sous_nature_bailleur",
                    models.CharField(
                        choices=[
                            ("ASSOCIATIONS", "Associations"),
                            ("ANAH", "ANAH"),
                            ("COMMERCIALES", "entreprises commerciales"),
                            ("COMMUNE", "Commune"),
                            ("COOPERATIVE_HLM_SCIC", "Sté coopérative HLM /SCIC"),
                            ("CROUS", "CROUS"),
                            ("DEPARTEMENT", "Département"),
                            ("DRE_DDE_CETE_AC_PREF", "DRE,DDE,CETE,AC,Préfect."),
                            ("EPCI", "EPCI"),
                            ("ETC_PUBLIQUE_LOCAL", "Ets public local"),
                            ("ETS_HOSTIPATIERS_PRIVES", "Ets hospitaliers privés"),
                            ("FONDATION", "Fondation"),
                            ("FONDATION_HLM", "Fondation HLM"),
                            ("FRONCIERE_LOGEMENT", "Foncière Logement"),
                            ("GIP", "GIP"),
                            ("MUTUELLE", "Mutuelle"),
                            ("NONRENSEIGNE", "Non renseigné"),
                            ("OFFICE_PUBLIC_HLM", "Office public HLM (OPH)"),
                            ("PACT_ARIM", "Pact-Arim"),
                            ("PARTICULIERS", "Particuliers"),
                            ("SA_HLM_ESH", "SA HLM / ESH"),
                            ("SACI_CAP", "SACI CAP"),
                            ("SEM_EPL", "SEM / EPL"),
                            ("UES", "UES"),
                        ],
                        default="NONRENSEIGNE",
                        max_length=25,
                    ),
                ),
                ("cree_le", models.DateTimeField(blank=True, editable=False)),
                ("mis_a_jour_le", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bailleurs.bailleur",
                    ),
                ),
                ("history_user_id", models.IntegerField(null=True)),
            ],
            options={
                "verbose_name": "historical bailleur",
                "verbose_name_plural": "historical bailleurs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
