# Generated by Django 3.2.5 on 2021-07-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0002_auto_20210723_1158"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bailleur",
            options={},
        ),
    ]
