# Generated by Django 3.2.7 on 2021-09-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bailleurs', '0003_alter_bailleur_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bailleur",
            name="capital_social",
        ),
        migrations.AddField(
            model_name='bailleur',
            name='capital_social',
            field=models.FloatField(null=True),
        ),
    ]
