# Generated by Django 3.2.11 on 2022-01-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0005_auto_20211201_1558"),
    ]

    operations = [
        migrations.AddField(
            model_name="bailleur",
            name="type_bailleur",
            field=models.CharField(
                choices=[
                    ("COLLECTIVITES", "Collectivités locales"),
                    ("COMMERCIALES", "Entreprises commerciales"),
                    ("HLM", "Entreprises HLM"),
                    ("NONRENSEIGNE", "Non renseigné"),
                    ("PERSONNEPHISIQUE", "Personnes physiques"),
                    ("TIERSSECTEUR", "Tiers secteur"),
                ],
                default="NONRENSEIGNE",
                max_length=25,
            ),
        ),
    ]
