# Generated by Django 3.2.11 on 2022-01-19 09:59

from django.db import migrations

from bailleurs.models import SousNatureBailleur


def normalize_enum_data(apps, schema_editor):

    Bailleur = apps.get_model("bailleurs", "Bailleur")

    for bailleur in Bailleur.objects.all():

        for value, label in SousNatureBailleur.choices:
            if bailleur.type_bailleur == label:
                bailleur.type_bailleur = value
        if bailleur.type_bailleur not in SousNatureBailleur.values:
            bailleur.type_bailleur = Bailleur.type_bailleur.field.default

        bailleur.save()


def nothing_to_do(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0006_bailleur_type_bailleur"),
    ]

    operations = [
        migrations.RunPython(normalize_enum_data, nothing_to_do),
    ]
