# Generated by Django 3.2.11 on 2022-01-19 09:59

from django.db import migrations

from bailleurs.models import TypeBailleur


def normalize_enum_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.

    Bailleur = apps.get_model("bailleurs", "Bailleur")

    for bailleur in Bailleur.objects.all():

        for value, label in TypeBailleur.choices:
            if bailleur.type_bailleur == label:
                bailleur.type_bailleur = value
        if bailleur.type_bailleur not in TypeBailleur.values:
            bailleur.type_bailleur = Bailleur.type_bailleur.field.default

        bailleur.save()


def nothing_to_do(apps, schema_editor):
    print("nothing to do")


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0006_bailleur_type_bailleur"),
    ]

    operations = [
        migrations.RunPython(normalize_enum_data, nothing_to_do),
    ]
