# Generated by Django 3.2.11 on 2022-01-20 14:06

import os

from django.db import migrations, models
from django.conf import settings

from openpyxl import load_workbook

from bailleurs.models import TypeBailleur


def update_type_bailleur(apps, schema_editor):

    Bailleur = apps.get_model("bailleurs", "Bailleur")

    basedir = settings.BASE_DIR
    file_path = os.path.join(basedir, "documents", "type_bailleurs.xlsx")
    wb = load_workbook(file_path, read_only=True)
    sheet_name = "Rapport 1"
    ws = wb[sheet_name]

    type_bailleur_by_label = {}
    for value, label in TypeBailleur.choices:
        type_bailleur_by_label[label] = value

    siret_by_cat = {}
    for row in ws.iter_rows(
        min_row=5, max_row=ws.max_row, min_col=1, max_col=ws.max_column
    ):
        siret = row[0].value
        cat = row[1].value
        if cat not in siret_by_cat:
            siret_by_cat[cat] = []
        siret_by_cat[cat].append(siret)

    for cat in siret_by_cat.keys():
        if cat is None:
            new_type_bailleur = TypeBailleur.NONRENSEIGNE
        else:
            new_type_bailleur = type_bailleur_by_label[cat]
        print(cat)
        print(new_type_bailleur)
        Bailleur.objects.filter(siret__in=siret_by_cat[cat]).update(
            type_bailleur=new_type_bailleur
        )


def nothing_to_do(apps, schema_editor):
    print("nothing to do")


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0007_auto_20220119_1059"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bailleur",
            name="type_bailleur",
            field=models.CharField(
                choices=[
                    ("ASSOCIATIONS", "Associations"),
                    ("COMMERCIALES", "entreprises commerciales"),
                    ("COMMUNE", "Commune"),
                    ("COOPERATIVE_HLM_SCIC", "Sté coopérative HLM /SCIC"),
                    ("CROUS", "CROUS"),
                    ("DEPARTEMENT", "Département"),
                    ("DRE_DDE_CETE_AC_PREF", "DRE,DDE,CETE,AC,Préfect."),
                    ("EPCI", "EPCI"),
                    ("ETC_PUBLIQUE_LOCAL", "Ets public local"),
                    ("ETS_HOSTIPATIERS_PRIVES", "Ets hospitaliers privés"),
                    ("FONDATION", "Fondation"),
                    ("FONDATION_HLM", "Fondation HLM"),
                    ("FRONCIERE_LOGEMENT", "Foncière Logement"),
                    ("GIP", "GIP"),
                    ("MUTUELLE", "Mutuelle"),
                    ("NONRENSEIGNE", "Non renseigné"),
                    ("OFFICE_PUBLIC_HLM", "Office public HLM (OPH)"),
                    ("PACT_ARIM", "Pact-Arim"),
                    ("PARTICULIERS", "Particuliers"),
                    ("SA_HLM_ESH", "SA HLM / ESH"),
                    ("SACI_CAP", "SACI CAP"),
                    ("SEM_EPL", "SEM / EPL"),
                    ("UES", "UES"),
                ],
                default="NONRENSEIGNE",
                max_length=25,
            ),
        ),
        migrations.RunPython(update_type_bailleur, nothing_to_do),
    ]
