# Generated by Django 3.2.11 on 2022-02-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0008_alter_bailleur_type_bailleur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bailleur",
            name="siret",
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
