# Generated by Django 3.2.13 on 2022-06-23 06:19

from django.db import migrations, models


def update_siren(apps, schema_editor):
    Bailleur = apps.get_model("bailleurs", "Bailleur")

    for bailleur in Bailleur.objects.all():
        bailleur.siren = bailleur.siret[:9]
        bailleur.save()


def nothing_to_do(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0009_alter_bailleur_siret"),
    ]

    operations = [
        migrations.AddField(
            model_name="bailleur",
            name="siren",
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.RunPython(update_siren, nothing_to_do),
    ]
