# Generated by Django 3.2.13 on 2022-06-02 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0009_alter_bailleur_siret"),
    ]

    operations = [
        migrations.CreateModel(
            name="Signataire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255, null=True)),
                ("fonction", models.CharField(max_length=255, null=True)),
                ("date_deliberation", models.DateField(null=True)),
                (
                    "bailleur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bailleurs.bailleur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SignatairePardefaut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bailleur",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bailleurs.bailleur",
                    ),
                ),
                (
                    "signataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bailleurs.signataire",
                    ),
                ),
            ],
        ),
    ]
