# Generated by Django 4.1.3 on 2022-11-07 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0010_bailleur_siren"),
    ]

    operations = [
        migrations.AddField(
            model_name="bailleur",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bailleurs",
                to="bailleurs.bailleur",
            ),
        ),
    ]
