# Generated by Django 3.2.13 on 2022-06-02 10:09

from django.db import migrations, models


def signataire_data(apps, schema_editor):
    Bailleur = apps.get_model("bailleurs", "Bailleur")
    Signataire = apps.get_model("bailleurs", "Signataire")

    for bailleursObj in Bailleur.objects.all():
        if bailleursObj.signataire_nom:
            signataire = Signataire(
                bailleur=bailleursObj,
                nom=bailleursObj.signataire_nom,
                fonction=bailleursObj.signataire_fonction,
                date_deliberation=bailleursObj.signataire_date_deliberation,
            )
            signataire.save()
            print(signataire)


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0010_signataire_signatairepardefaut"),
    ]

    operations = [migrations.RunPython(signataire_data, migrations.RunPython.noop)]
