# Generated by Django 3.2.13 on 2022-06-02 10:09

from django.db import migrations, models


def signatairepardefaut_data(apps, schema_editor):
    Signataire = apps.get_model("bailleurs", "Signataire")
    SignatairePardefaut = apps.get_model("bailleurs", "SignatairePardefaut")

    for signatairesObj in Signataire.objects.all():
        signatairepardefaut = SignatairePardefaut(
            bailleur=signatairesObj.bailleur, signataire=signatairesObj
        )
        signatairepardefaut.save()
        print(signatairepardefaut)


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0011_data_signataire"),
    ]

    operations = [
        migrations.RunPython(signatairepardefaut_data, migrations.RunPython.noop)
    ]
