# Generated by Django 4.1.3 on 2022-11-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0011_bailleur_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bailleur",
            old_name="type_bailleur",
            new_name="sous_nature_bailleur",
        ),
    ]
