# Generated by Django 4.1.3 on 2022-11-21 15:43

from django.db import migrations, models

from bailleurs.models import NATURE_RELATIONSHIP


def set_nature_bailleur(apps, schema_editor):
    Bailleur = apps.get_model("bailleurs", "Bailleur")
    for sous_nature, nature in NATURE_RELATIONSHIP.items():
        Bailleur.objects.filter(sous_nature_bailleur=sous_nature).update(
            nature_bailleur=nature
        )


class Migration(migrations.Migration):
    dependencies = [
        ("bailleurs", "0012_rename_type_bailleur_bailleur_sous_nature_bailleur"),
    ]

    operations = [
        migrations.AddField(
            model_name="bailleur",
            name="nature_bailleur",
            field=models.CharField(
                choices=[
                    (
                        "Autres bailleurs sociaux non HLM",
                        "Autres bailleurs sociaux non HLM",
                    ),
                    ("Bailleurs privés", "Bailleurs privés"),
                    ("HLM", "HLM"),
                    ("SEM", "SEM"),
                ],
                default="Autres bailleurs sociaux non HLM",
                max_length=255,
            ),
        ),
        migrations.RunPython(set_nature_bailleur, migrations.RunPython.noop),
    ]
