# Generated by Django 4.1.3 on 2022-11-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0013_bailleur_nature_bailleur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bailleur",
            name="capital_social",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bailleur",
            name="operation_exceptionnelle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bailleur",
            name="signataire_date_deliberation",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bailleur",
            name="signataire_fonction",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bailleur",
            name="signataire_nom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
