# Generated by Django 4.1.5 on 2023-01-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0015_alter_bailleur_sous_nature_bailleur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bailleur",
            name="siret",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
