# Generated by Django 4.1.5 on 2023-02-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0016_alter_bailleur_siret"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bailleur",
            name="adresse",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bailleur",
            name="code_postal",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="bailleur",
            name="ville",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
