# Generated by Django 4.1.5 on 2023-02-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bailleurs",
            "0017_alter_bailleur_adresse_alter_bailleur_code_postal_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bailleur",
            name="signataire_bloc_signature",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
