# Generated by Django 4.1.7 on 2023-03-14 09:19

from django.db import migrations, models


def assign_siren(apps, schema_editor):
    Bailleur = apps.get_model("bailleurs", "Bailleur")

    for bailleur in Bailleur.objects.all():
        if len(bailleur.siret) == 14 and bailleur.siret.isdigit():
            bailleur.siren = bailleur.siret[:9]
        else:
            bailleur.siren = bailleur.siret
        bailleur.save()


class Migration(migrations.Migration):

    dependencies = [
        ("bailleurs", "0018_bailleur_signataire_bloc_signature"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bailleur",
            name="siren",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(assign_siren, migrations.RunPython.noop),
    ]
