# Generated by Django 4.1.7 on 2023-04-03 10:20

import uuid

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bailleurs", "0019_auto_20230314_1019"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalBailleur",
            fields=[
                ("id", models.IntegerField(blank=True, db_index=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("nom", models.CharField(max_length=255)),
                ("siret", models.CharField(db_index=True, max_length=255)),
                ("siren", models.CharField(max_length=255, null=True)),
                ("capital_social", models.FloatField(blank=True, null=True)),
                ("adresse", models.CharField(blank=True, max_length=255, null=True)),
                ("code_postal", models.CharField(blank=True, max_length=5, null=True)),
                ("ville", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "signataire_nom",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "signataire_fonction",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "signataire_date_deliberation",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "signataire_bloc_signature",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                ("operation_exceptionnelle", models.TextField(blank=True, null=True)),
                (
                    "nature_bailleur",
                    models.CharField(
                        choices=[
                            (
                                "Autres bailleurs sociaux non HLM",
                                "Autres bailleurs sociaux non HLM",
                            ),
                            ("Bailleurs privés", "Bailleurs privés"),
                            ("HLM", "HLM"),
                            ("SEM", "SEM"),
                        ],
                        default="Autres bailleurs sociaux non HLM",
                        max_length=255,
                    ),
                ),
                (
                    "sous_nature_bailleur",
                    models.CharField(
                        choices=[
                            ("ASSOCIATIONS", "Associations"),
                            ("ANAH", "ANAH"),
                            ("COMMERCIALES", "entreprises commerciales"),
                            ("COMMUNE", "Commune"),
                            ("COOPERATIVE_HLM_SCIC", "Sté coopérative HLM /SCIC"),
                            ("CROUS", "CROUS"),
                            ("DEPARTEMENT", "Département"),
                            ("DRE_DDE_CETE_AC_PREF", "DRE,DDE,CETE,AC,Préfect."),
                            ("EPCI", "EPCI"),
                            ("ETC_PUBLIQUE_LOCAL", "Ets public local"),
                            ("ETS_HOSTIPATIERS_PRIVES", "Ets hospitaliers privés"),
                            ("FONDATION", "Fondation"),
                            ("FONDATION_HLM", "Fondation HLM"),
                            ("FRONCIERE_LOGEMENT", "Foncière Logement"),
                            ("GIP", "GIP"),
                            ("MUTUELLE", "Mutuelle"),
                            ("NONRENSEIGNE", "Non renseigné"),
                            ("OFFICE_PUBLIC_HLM", "Office public HLM (OPH)"),
                            ("PACT_ARIM", "Pact-Arim"),
                            ("PARTICULIERS", "Particuliers"),
                            ("SA_HLM_ESH", "SA HLM / ESH"),
                            ("SACI_CAP", "SACI CAP"),
                            ("SEM_EPL", "SEM / EPL"),
                            ("UES", "UES"),
                        ],
                        default="NONRENSEIGNE",
                        max_length=25,
                    ),
                ),
                ("cree_le", models.DateTimeField(blank=True, editable=False)),
                ("mis_a_jour_le", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="bailleurs.bailleur",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical bailleur",
                "verbose_name_plural": "historical bailleurs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
