# Generated by Django 4.1.7 on 2023-04-10 13:30
from django.db import migrations
from django.db.models import Count


def resolve_duplicate(apps, schema_editor):

    Bailleur = apps.get_model("bailleurs", "Bailleur")

    for bailleur_siren in (
        Bailleur.objects.values("siren").annotate(count=Count("pk")).filter(count__gt=1)
    ):
        same_bailleurs = (
            Bailleur.objects.values("uuid")
            .annotate(role_count=Count("roles"))
            .filter(siren=bailleur_siren["siren"])
        )
        sorted_same_bailleurs = sorted(
            same_bailleurs, key=lambda k: k["role_count"], reverse=True
        )
        kept_bailleur = Bailleur.objects.get(uuid=sorted_same_bailleurs[0]["uuid"])
        for sorted_same_bailleur in sorted_same_bailleurs[1:]:
            removed_bailleur = Bailleur.objects.get(uuid=sorted_same_bailleur["uuid"])
            removed_bailleur.programme_set.update(bailleur_id=kept_bailleur.id)
            removed_bailleur.roles.update(bailleur_id=kept_bailleur.id)
            Bailleur.objects.filter(uuid=removed_bailleur.uuid).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("bailleurs", "0021_remove_historicalbailleur_history_user_and_more"),
    ]

    operations = [
        migrations.RunPython(resolve_duplicate, migrations.RunPython.noop),
    ]
