# Generated by Django 4.1.7 on 2023-04-10 14:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bailleurs", "0022_auto_20230410_1530"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bailleur",
            name="siren",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="bailleur",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalbailleur",
            name="siren",
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalbailleur",
            name="uuid",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
