# Generated by Django 4.2.9 on 2024-01-29 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bailleurs", "0024_bailleur_search_vector_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                DROP TRIGGER IF EXISTS search_vector_trigger_bailleur ON bailleurs_bailleur;
                DROP FUNCTION IF EXISTS search_vector_bailleur_func;

                CREATE FUNCTION search_vector_bailleur_func() RETURNS trigger AS $$
                begin
                new.search_vector :=
                    setweight(to_tsvector('pg_catalog.french', coalesce(new.nom,'')), 'A') ||
                    setweight(to_tsvector('pg_catalog.french', coalesce(new.siret,'')), 'B') ||
                    setweight(to_tsvector('pg_catalog.french', coalesce(new.siren,'')), 'C');
                return new;
                end
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER search_vector_trigger_bailleur
                BEFORE INSERT OR UPDATE OF nom, siret, siren
                ON bailleurs_bailleur
                FOR EACH ROW EXECUTE FUNCTION search_vector_bailleur_func();
            """,
            reverse_sql="""
                DROP TRIGGER IF EXISTS search_vector_trigger_bailleur ON bailleurs_bailleur;
                DROP FUNCTION IF EXISTS search_vector_bailleur_func;
            """,
        ),
    ]
