# Generated by Django 4.2.9 on 2024-02-19 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bailleurs", "0025_search_vector_trigger"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="bailleur",
            name="search_vector_bailleur_idx",
        ),
        migrations.RemoveField(
            model_name="bailleur",
            name="search_vector",
        ),
        migrations.RemoveField(
            model_name="historicalbailleur",
            name="search_vector",
        ),
    ]
