# Generated by Django 4.1.7 on 2023-03-08 21:35

from django.db import migrations, models
import django.db.migrations.operations.special


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# apilos_settings.migrations.0004_auto_20230207_2328


class Migration(migrations.Migration):

    replaces = [
        ("apilos_settings", "0001_initial"),
        ("apilos_settings", "0002_auto_20220317_1211"),
        ("apilos_settings", "0003_departement_code_insee_region"),
        ("apilos_settings", "0004_auto_20230207_2328"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255, unique=True)),
                ("code_insee", models.CharField(max_length=3, unique=True)),
                ("code_postal", models.CharField(max_length=3)),
                ("code_insee_region", models.CharField(default=0, max_length=2)),
            ],
        ),
    ]
