# Generated by Django 3.2.12 on 2022-03-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("code_insee", models.CharField(max_length=3)),
                ("code_postal", models.CharField(max_length=3)),
            ],
        ),
    ]
