# Generated by Django 3.2.12 on 2022-03-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apilos_settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departement",
            name="code_insee",
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name="departement",
            name="nom",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
