# Generated by Django 4.1.5 on 2023-02-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apilos_settings", "0002_auto_20220317_1211"),
    ]

    operations = [
        migrations.AddField(
            model_name="departement",
            name="code_insee_region",
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
