# Generated by Django 4.1.7 on 2023-03-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apilos_settings", "0001_initial_squashed_0004_auto_20230207_2328"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departement",
            name="code_insee_region",
            field=models.CharField(max_length=2),
        ),
    ]
