version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
        environment:
          DATABASE_URL: postgres://root:password@localhost/appel_test
          SECRET_KEY: secret-key
          DEBUG: False
      - image: circleci/postgres:12.2-postgis
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: appel_test
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Wait for Postgres server
          command: dockerize -wait tcp://localhost:5432 -timeout 10s
      - run:
          name: Run database migrations
          command: |
            . venv/bin/activate
            python3 ./manage.py migrate
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app
