# Generated by Django 4.2.11 on 2024-04-17 13:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("comments", "0001_initial"),
        ("comments", "0002_alter_comment_uuid_objet"),
        ("comments", "0003_comment_comment_statut_idx"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conventions", "0012_alter_pret_montant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("nom_objet", models.CharField(max_length=255)),
                ("champ_objet", models.CharField(max_length=255)),
                ("uuid_objet", models.UUIDField(null=True)),
                ("message", models.TextField(null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("OUVERT", "Ouvert"),
                            ("RESOLU", "Résolu"),
                            ("CLOS", "Commentaire clos"),
                        ],
                        default="OUVERT",
                        max_length=25,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("mis_a_jour_le", models.DateTimeField(auto_now=True)),
                ("resolu_le", models.DateTimeField(null=True)),
                ("clos_le", models.DateTimeField(null=True)),
                (
                    "convention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conventions.convention",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["statut"], name="comment_statut_idx")],
            },
        ),
    ]
