# Generated by Django 3.2.8 on 2021-10-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="clos_le",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="resolu_le",
            field=models.DateTimeField(null=True),
        ),
    ]
