# Generated by Django 3.2.12 on 2022-02-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="uuid_objet",
            field=models.UUIDField(null=True),
        ),
    ]
