# Generated by Django 4.2.11 on 2024-04-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("ecoloweb", "0001_create_ecolo_reference"),
        ("ecoloweb", "0002_add_import_context"),
        ("ecoloweb", "0003_ecolo_ref_est_supprime"),
        ("ecoloweb", "0004_purge_duplicate_bailleurs"),
        ("ecoloweb", "0005_ecoloreference_apilos_model_id_idx"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EcoloReference",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("apilos_model", models.CharField(max_length=64)),
                ("ecolo_id", models.TextField(max_length=32)),
                ("apilos_id", models.IntegerField()),
                ("departement", models.CharField(default=None, max_length=3)),
                ("importe_le", models.DateField(null=True)),
                ("est_supprime", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {("apilos_model", "ecolo_id")},
                "indexes": [
                    models.Index(
                        fields=["apilos_model", "apilos_id"], name="apilos_model_id_idx"
                    )
                ],
            },
        ),
    ]
