# Generated by Django 4.1.3 on 2022-11-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecoloweb", "0001_create_ecolo_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecoloreference",
            name="departement",
            field=models.CharField(default=None, max_length=3),
        ),
        migrations.AddField(
            model_name="ecoloreference",
            name="importe_le",
            field=models.DateField(null=True),
        ),
    ]
