# Generated by Django 4.1.3 on 2022-11-28 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecoloweb", "0001_create_ecolo_reference"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ecoloreference",
            unique_together={
                ("apilos_model", "apilos_id"),
                ("apilos_model", "ecolo_id"),
            },
        ),
    ]
