# Generated by Django 4.1.7 on 2023-04-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecoloweb", "0002_add_import_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="ecoloreference",
            name="est_supprime",
            field=models.BooleanField(default=False),
        ),
    ]
