# Generated by Django 4.2.11 on 2024-04-17 13:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("upload", "0001_initial"),
        ("upload", "0002_rename_uploadedfiles_uploadedfile"),
        ("upload", "0003_uploadedfile_content_type"),
        ("upload", "0004_auto_20211018_1351"),
        ("upload", "0005_alter_uploadedfile_dirpath"),
        ("upload", "0006_auto_20220107_1209"),
    ]

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("filename", models.CharField(max_length=255, null=True)),
                ("size", models.CharField(max_length=255, null=True)),
                ("content_type", models.CharField(max_length=255, null=True)),
                ("dirpath", models.CharField(max_length=255, null=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("mis_a_jour_le", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
