# Generated by Django 3.2.7 on 2021-09-30 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UploadedFiles",
            new_name="UploadedFile",
        ),
    ]
