# Generated by Django 3.2.7 on 2021-09-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0002_rename_uploadedfiles_uploadedfile"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="content_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
