# Generated by Django 3.2.7 on 2021-10-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0003_uploadedfile_content_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="filepath",
        ),
        migrations.RemoveField(
            model_name="uploadedfile",
            name="thumbnail",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="dirpath",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
