# Generated by Django 5.1 on 2024-08-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0007_uploadedfile_realname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="filename",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="realname",
            field=models.CharField(max_length=255),
        ),
    ]
