# Generated by Django 4.2.15 on 2024-11-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload", "0008_alter_uploadedfile_filename_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="filename",
            field=models.CharField(
                help_text="le nom du fichier utilisé pour le stockage", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="realname",
            field=models.CharField(
                help_text="Nom réel du fichier lors de l'Upload, il est ré-utilisé lors du download et à l'affichage",
                max_length=255,
            ),
        ),
    ]
