foyer_attribution_success_payload = {
    "attribution_reservation_prefectorale": "10",
    "attribution_type": "agees",
    "attribution_agees_autonomie": "FALSE",
    "attribution_agees_ephad": "FALSE",
    "attribution_agees_desorientees": "FALSE",
    "attribution_agees_petite_unite": "FALSE",
    "attribution_agees_autre": "on",
    "attribution_agees_autre_detail": "yo",
    "attribution_handicapes_foyer": "FALSE",
    "attribution_handicapes_foyer_de_vie": "FALSE",
    "attribution_handicapes_foyer_medicalise": "FALSE",
    "attribution_handicapes_autre": "FALSE",
    "attribution_handicapes_autre_detail": "",
    "attribution_inclusif_conditions_specifiques": "",
    "attribution_inclusif_conditions_admission": "",
    "attribution_inclusif_modalites_attribution": "",
    "attribution_inclusif_partenariats": "",
    "attribution_inclusif_activites": "",
    "attribution_modalites_reservations": "test",
    "attribution_modalites_choix_personnes": "Top !!!",
    "attribution_prestations_integrees": "OKOK",
    "attribution_prestations_facultatives": "",
}

residence_attribution_success_payload = {
    "attribution_reservation_prefectorale": "10",
    "attribution_residence_sociale_ordinaire": "on",
    "attribution_pension_de_famille": "on",
    "attribution_residence_accueil": "FALSE",
    "attribution_modalites_reservations": "test",
    "attribution_modalites_choix_personnes": "Top !!!",
    "attribution_prestations_integrees": "OKOK",
    "attribution_prestations_facultatives": "",
}

variantes_success_payload = {
    "foyer_residence_variante_1": "on",
    "foyer_residence_variante_2": "on",
    "foyer_residence_variante_2_travaux": "TRAVAUX",
    "foyer_residence_variante_2_nb_annees": "2",
    "foyer_residence_variante_2_nb_tranches": "2",
    "foyer_residence_variante_3": "on",
}

foyer_residence_logements_success_payload = {
    "form-TOTAL_FORMS": "2",
    "form-INITIAL_FORMS": "2",
    "form-0-uuid": "",
    "form-0-designation": "B1",
    "form-0-typologie": "T1prime",
    "form-0-surface_habitable": "12.12",
    "form-0-loyer": "135.00",
    "form-1-uuid": "",
    "form-1-designation": "B2",
    "form-1-typologie": "T1prime",
    "form-1-surface_habitable": "30.00",
    "form-1-loyer": "135.00",
    "surface_habitable_totale": "50.55",
    "nb_logements": "2",
}

collectif_success_payload = {
    "form-TOTAL_FORMS": "2",
    "form-INITIAL_FORMS": "2",
    "form-0-type_local": "Bli",
    "form-0-surface_habitable": "12.12",
    "form-0-nombre": "12",
    "form-1-type_local": "bla",
    "form-1-surface_habitable": "50.00",
    "form-1-nombre": "1",
    "foyer_residence_nb_garage_parking": "2",
    "foyer_residence_dependance": "bli",
    "foyer_residence_locaux_hors_convention": "bla",
}

logement_success_payload = {
    "avec_loyer-TOTAL_FORMS": "2",
    "avec_loyer-INITIAL_FORMS": "2",
    "avec_loyer-0-uuid": "",
    "avec_loyer-0-designation": "B1",
    "avec_loyer-0-typologie": "T1",
    "avec_loyer-0-surface_habitable": "12.12",
    "avec_loyer-0-surface_annexes": "45.57",
    "avec_loyer-0-surface_annexes_retenue": "0.00",
    "avec_loyer-0-surface_utile": "30.00",
    "avec_loyer-0-loyer_par_metre_carre": "4.5",
    "avec_loyer-0-coeficient": "1.0000",
    "avec_loyer-0-loyer": "135.00",
    "avec_loyer-0-import_order": "0",
    "avec_loyer-1-uuid": "",
    "avec_loyer-1-designation": "B2",
    "avec_loyer-1-typologie": "T1",
    "avec_loyer-1-surface_habitable": "30.00",
    "avec_loyer-1-surface_annexes": "0.00",
    "avec_loyer-1-surface_annexes_retenue": "0.00",
    "avec_loyer-1-surface_utile": "30.00",
    "avec_loyer-1-loyer_par_metre_carre": "4.5",
    "avec_loyer-1-coeficient": "1.0000",
    "avec_loyer-1-loyer": "135.00",
    "avec_loyer-1-import_order": "1",
    "sans_loyer-TOTAL_FORMS": "0",
    "sans_loyer-INITIAL_FORMS": "0",
    "corrigee_avec_loyer-TOTAL_FORMS": "0",
    "corrigee_avec_loyer-INITIAL_FORMS": "0",
    "corrigee_sans_loyer-TOTAL_FORMS": "0",
    "corrigee_sans_loyer-INITIAL_FORMS": "0",
    "loyer_derogatoire": "10",
    "surface_locaux_collectifs_residentiels": "25",
    "lgts_mixite_sociale_negocies": "2",
    "nb_logements": "2",
}
