attribution_success_payload = {
    "attribution_reservation_prefectoral": "10",
    "attribution_type": "agees",
    "attribution_agees_autonomie": "FALSE",
    "attribution_agees_ephad": "FALSE",
    "attribution_agees_desorientees": "FALSE",
    "attribution_agees_petite_unite": "FALSE",
    "attribution_agees_autre": "on",
    "attribution_agees_autre_detail": "yo",
    "attribution_handicapes_foyer": "FALSE",
    "attribution_handicapes_foyer_de_vie": "FALSE",
    "attribution_handicapes_foyer_medicalise": "FALSE",
    "attribution_handicapes_autre": "FALSE",
    "attribution_handicapes_autre_detail": "",
    "attribution_inclusif_conditions_specifiques": "",
    "attribution_inclusif_conditions_admission": "",
    "attribution_inclusif_modalites_attribution": "",
    "attribution_inclusif_partenariats": "",
    "attribution_inclusif_activites": "",
    "attribution_modalites_reservations": "test",
    "attribution_modalites_choix_personnes": "Top !!!",
    "attribution_prestations_integrees": "OKOK",
    "attribution_prestations_facultatives": "",
}

variantes_success_payload = {
    "foyer_variante_1": "on",
    "foyer_variante_2": "on",
    "foyer_variante_2_travaux": "TRAVAUX",
    "foyer_variante_3": "on",
}

foyer_residence_logements_success_payload = {
    "form-TOTAL_FORMS": "2",
    "form-INITIAL_FORMS": "2",
    "form-0-uuid": "",
    "form-0-designation": "B1",
    "form-0-typologie": "T1prime",
    "form-0-surface_habitable": "12.12",
    "form-0-loyer": "135.00",
    "form-1-uuid": "",
    "form-1-designation": "B2",
    "form-1-typologie": "T1prime",
    "form-1-surface_habitable": "30.00",
    "form-1-loyer": "135.00",
    "surface_habitable_totale": "50.55",
}
