attribution_success_payload = {
    "attribution_reservation_prefectoral": "10",
    "attribution_type": "agees",
    "attribution_agees_autonomie": "FALSE",
    "attribution_agees_ephad": "FALSE",
    "attribution_agees_desorientees": "FALSE",
    "attribution_agees_petite_unite": "FALSE",
    "attribution_agees_autre": "on",
    "attribution_agees_autre_detail": "yo",
    "attribution_handicapes_foyer": "FALSE",
    "attribution_handicapes_foyer_de_vie": "FALSE",
    "attribution_handicapes_foyer_medicalise": "FALSE",
    "attribution_handicapes_autre": "FALSE",
    "attribution_handicapes_autre_detail": "",
    "attribution_inclusif_conditions_specifiques": "",
    "attribution_inclusif_conditions_admission": "",
    "attribution_inclusif_modalites_attribution": "",
    "attribution_inclusif_partenariats": "",
    "attribution_inclusif_activites": "",
    "attribution_modalites_reservations": "test",
    "attribution_modalites_choix_personnes": "Top !!!",
    "attribution_prestations_integrees": "OKOK",
    "attribution_prestations_facultatives": "",
}

variantes_success_payload = {
    "foyer_variante_1": "on",
    "foyer_variante_2": "on",
    "foyer_variante_2_travaux": "TRAVAUX",
    "foyer_variante_3": "on",
}
