# Generated by Django 3.2.5 on 2021-09-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructeurs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="administration",
            name="ville_signature",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
