# Generated by Django 3.2.11 on 2022-02-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructeurs", "0003_auto_20220107_1209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administration",
            name="code",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="administration",
            name="nom",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
