# Generated by Django 3.2.13 on 2022-05-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructeurs", "0004_auto_20220202_1444"),
    ]

    operations = [
        migrations.AddField(
            model_name="administration",
            name="prefix_convention",
            field=models.CharField(
                default="{département}/{zone}/{mois}/{année}/80.416/",
                max_length=255,
                null=True,
            ),
        ),
    ]
