# Generated by Django 3.2.13 on 2022-06-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructeurs", "0005_administration_prefix_convention"),
    ]

    operations = [
        migrations.AddField(
            model_name="administration",
            name="adresse",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="administration",
            name="code_postal",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="administration",
            name="ville",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
