# Generated by Django 3.2.13 on 2022-06-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructeurs", "0006_auto_20220601_1653"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administration",
            name="adresse",
            field=models.TextField(null=True),
        ),
    ]
