# Generated by Django 3.2.13 on 2022-06-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructeurs", "0007_alter_administration_adresse"),
    ]

    operations = [
        migrations.AddField(
            model_name="administration",
            name="nb_convention_exemplaires",
            field=models.IntegerField(default=3),
        ),
    ]
