# Generated by Django 4.1.5 on 2023-01-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructeurs", "0008_administration_nb_convention_exemplaires"),
    ]

    operations = [
        migrations.AddField(
            model_name="administration",
            name="signature_label_extra",
            field=models.TextField(null=True),
        ),
    ]
