# Generated by Django 4.1.5 on 2023-02-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructeurs", "0010_alter_administration_signature_label_extra"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administration",
            name="adresse",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="administration",
            name="code_postal",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="administration",
            name="ville",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
