# Generated by Django 4.1.5 on 2023-02-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instructeurs", "0011_alter_administration_adresse_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="administration",
            old_name="signature_label_extra",
            new_name="signataire_bloc_signature",
        ),
    ]
