# Generated by Django 4.1.7 on 2023-04-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructeurs", "0013_historicaladministration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaladministration",
            name="history_user",
        ),
        migrations.AddField(
            model_name="historicaladministration",
            name="history_user_id",
            field=models.IntegerField(null=True),
        ),
    ]
