# Generated by Django 4.2 on 2023-05-22 10:42

from django.db import migrations, models


def setup_code_dans_galion(apps, schema_editor):
    Administration = apps.get_model("instructeurs", "Administration")
    for administration in Administration.objects.all():
        administration.code_dans_galion = administration.code
        administration.save()


class Migration(migrations.Migration):
    dependencies = [
        ("instructeurs", "0014_remove_historicaladministration_history_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administration",
            name="nom",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="historicaladministration",
            name="nom",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="administration",
            name="code_dans_galion",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaladministration",
            name="code_dans_galion",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(setup_code_dans_galion, migrations.RunPython.noop),
    ]
