# Generated by Django 4.2 on 2023-05-22 10:48

from django.db import migrations
from django.db.models import Q
from django.forms.models import model_to_dict

from programmes.models import Programme
from users.models import Role


def move_dd_to_ddi(apps, schema_editor):
    Administration = apps.get_model("instructeurs", "Administration")
    for administration in Administration.objects.filter(
        Q(code__startswith="DD0") | Q(code__startswith="DD9")
    ):
        new_administration = Administration.objects.filter(
            code="DDI" + administration.code[2:]
        ).first()
        if not new_administration:
            new_administration = Administration.objects.create(
                code="DDI" + administration.code[2:],
                **model_to_dict(administration, exclude=["id", "code"]),
            )
        Role.objects.filter(administration=administration).update(
            administration=new_administration
        )
        Programme.objects.filter(administration=administration).update(
            administration=new_administration
        )


class Migration(migrations.Migration):
    dependencies = [
        ("instructeurs", "0015_administration_code_dans_galion_and_more"),
    ]

    operations = [migrations.RunPython(move_dd_to_ddi, migrations.RunPython.noop)]
