# Generated by Django 4.2.3 on 2023-09-25 10:09

from django.db import migrations


def foobar(apps, schema_editor):
    Administration = apps.get_model("instructeurs", "Administration")

    for administration in Administration.objects.all():
        if administration.nom.endswith(f" ({administration.code})"):
            administration.nom = administration.nom.split("(", 1)[0].strip()
            administration.save()
        if administration.nom.startswith(f"{administration.code} - "):
            administration.nom = administration.nom.split(" - ", 1)[1].strip()
            administration.save()


class Migration(migrations.Migration):
    dependencies = [
        ("instructeurs", "0016_auto_20230522_1248"),
    ]

    operations = [
        migrations.RunPython(foobar, migrations.RunPython.noop),
    ]
