from django.core.management.base import BaseCommand

from programmes.models import Programme


class Command(BaseCommand):
    def handle(self, *args, **options):

        mapping_pc_dpt = {}
        for data in corse_insee_data:
            code_postal = data.get("postal_code")
            code_insee_departement = data.get("code_dept")
            mapping_pc_dpt[code_postal] = code_insee_departement

        for code_postal, code_insee_departement in mapping_pc_dpt.items():
            rows = (
                Programme.objects.filter(code_postal=code_postal)
                .exclude(code_insee_departement=code_insee_departement)
                .update(code_insee_departement=code_insee_departement)
            )
            self.stdout.write(
                f"Postal code {code_postal} to {code_insee_departement} : {rows} rows updated."
            )


# Sopurce: https://public.opendatasoft.com/explore/dataset/correspondance-code-insee-code-postal/table/?dataChart=eyJxdWVyaWVzIjpbeyJjb25maWciOnsiZGF0YXNldCI6ImNvcnJlc3BvbmRhbmNlLWNvZGUtaW5zZWUtY29kZS1wb3N0YWwiLCJvcHRpb25zIjp7InRhYiI6ImFuYWx5emUifX0sImNoYXJ0cyI6W3sidHlwZSI6ImNvbHVtbiIsImZ1bmMiOiJBVkciLCJ5QXhpcyI6InpfbW95ZW4iLCJjb2xvciI6IiM2NmMyYTUifV0sInhBeGlzIjoibm9tX2RlcHQiLCJtYXhwb2ludHMiOjUwLCJzb3J0IjoiIn1dfQ%3D%3D&sort=nom_comm&refine.nom_region=CORSE&location=10,48.56797,3.71132&basemap=mapquest
corse_insee_data = [
    {
        "insee_com": "2B009",
        "postal_code": "20270",
        "nom_comm": "ALERIA",
        "code_comm": "009",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B353",
        "postal_code": "20200",
        "nom_comm": "VILLE-DI-PIETRABUGNO",
        "code_comm": "353",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B073",
        "postal_code": "20224",
        "nom_comm": "CASAMACCIOLI",
        "code_comm": "073",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B321",
        "postal_code": "20234",
        "nom_comm": "TARRANO",
        "code_comm": "321",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B230",
        "postal_code": "20246",
        "nom_comm": "PIEVE",
        "code_comm": "230",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B236",
        "postal_code": "20240",
        "nom_comm": "POGGIO-DI-NAZZA",
        "code_comm": "236",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B306",
        "postal_code": "20250",
        "nom_comm": "SANTA-LUCIA-DI-MERCURIO",
        "code_comm": "306",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B343",
        "postal_code": "20215",
        "nom_comm": "VENZOLASCA",
        "code_comm": "343",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A278",
        "postal_code": "20127",
        "nom_comm": "SERRA-DI-SCOPAMENE",
        "code_comm": "278",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B327",
        "postal_code": "20248",
        "nom_comm": "TOMINO",
        "code_comm": "327",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B201",
        "postal_code": "20251/20270",
        "nom_comm": "PANCHERACCIA",
        "code_comm": "201",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A128",
        "postal_code": "20100",
        "nom_comm": "GRANACE",
        "code_comm": "128",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B124",
        "postal_code": "20227",
        "nom_comm": "GHISONI",
        "code_comm": "124",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A259",
        "postal_code": "20121",
        "nom_comm": "REZZA",
        "code_comm": "259",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A266",
        "postal_code": "20121",
        "nom_comm": "SALICE",
        "code_comm": "266",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B063",
        "postal_code": "20229",
        "nom_comm": "CARCHETO-BRUSTICO",
        "code_comm": "063",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B030",
        "postal_code": "20228",
        "nom_comm": "BARRETTALI",
        "code_comm": "030",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A027",
        "postal_code": "20121",
        "nom_comm": "AZZANA",
        "code_comm": "027",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B245",
        "postal_code": "20215",
        "nom_comm": "PORRI",
        "code_comm": "245",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A132",
        "postal_code": "20128",
        "nom_comm": "GUARGUALE",
        "code_comm": "132",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A032",
        "postal_code": "20129",
        "nom_comm": "BASTELICACCIA",
        "code_comm": "032",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A211",
        "postal_code": "20140",
        "nom_comm": "PETRETO-BICCHISANO",
        "code_comm": "211",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B125",
        "postal_code": "20237",
        "nom_comm": "GIOCATOJO",
        "code_comm": "125",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B169",
        "postal_code": "20218",
        "nom_comm": "MOROSAGLIA",
        "code_comm": "169",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A212",
        "postal_code": "20115",
        "nom_comm": "PIANA",
        "code_comm": "212",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B194",
        "postal_code": "20234",
        "nom_comm": "ORTALE",
        "code_comm": "194",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B328",
        "postal_code": "20270",
        "nom_comm": "TOX",
        "code_comm": "328",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A090",
        "postal_code": "20160",
        "nom_comm": "COGGIA",
        "code_comm": "090",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B147",
        "postal_code": "20224",
        "nom_comm": "LOZZI",
        "code_comm": "147",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A282",
        "postal_code": "20125",
        "nom_comm": "SOCCIA",
        "code_comm": "282",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A326",
        "postal_code": "20117",
        "nom_comm": "TOLLA",
        "code_comm": "326",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B084",
        "postal_code": "20225",
        "nom_comm": "CATERI",
        "code_comm": "084",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A247",
        "postal_code": "20137",
        "nom_comm": "PORTO-VECCHIO",
        "code_comm": "247",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B224",
        "postal_code": "20233",
        "nom_comm": "PIETRACORBARA",
        "code_comm": "224",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A141",
        "postal_code": "20160",
        "nom_comm": "LETIA",
        "code_comm": "141",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A066",
        "postal_code": "20164",
        "nom_comm": "CARGIACA",
        "code_comm": "066",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A091",
        "postal_code": "20123",
        "nom_comm": "COGNOCOLI-MONTICCHI",
        "code_comm": "091",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A026",
        "postal_code": "20190",
        "nom_comm": "AZILONE-AMPAZA",
        "code_comm": "026",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B292",
        "postal_code": "20212",
        "nom_comm": "SANT'ANDREA-DI-BOZIO",
        "code_comm": "292",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B293",
        "postal_code": "20221",
        "nom_comm": "SANT'ANDREA-DI-COTONE",
        "code_comm": "293",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B238",
        "postal_code": "20250",
        "nom_comm": "POGGIO-DI-VENACO",
        "code_comm": "238",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B221",
        "postal_code": "20229",
        "nom_comm": "PIEDIPARTINO",
        "code_comm": "221",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B365",
        "postal_code": "20243",
        "nom_comm": "SAN-GAVINO-DI-FIUMORBO",
        "code_comm": "365",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B214",
        "postal_code": "20215",
        "nom_comm": "PIANO",
        "code_comm": "214",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B029",
        "postal_code": "20253",
        "nom_comm": "BARBAGGIO",
        "code_comm": "029",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A094",
        "postal_code": "20168",
        "nom_comm": "CORRANO",
        "code_comm": "094",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B177",
        "postal_code": "20242",
        "nom_comm": "NOCETA",
        "code_comm": "177",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A139",
        "postal_code": "20137",
        "nom_comm": "LECCI",
        "code_comm": "139",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A359",
        "postal_code": "20132",
        "nom_comm": "ZICAVO",
        "code_comm": "359",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B188",
        "postal_code": "20232",
        "nom_comm": "OLMETA-DI-TUDA",
        "code_comm": "188",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B280",
        "postal_code": "20215",
        "nom_comm": "SILVARECCIO",
        "code_comm": "280",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B106",
        "postal_code": "20244",
        "nom_comm": "ERONE",
        "code_comm": "106",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B342",
        "postal_code": "20240",
        "nom_comm": "VENTISERI",
        "code_comm": "342",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B302",
        "postal_code": "20230",
        "nom_comm": "SAN-GIOVANNI-DI-MORIANI",
        "code_comm": "302",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B361",
        "postal_code": "20214",
        "nom_comm": "ZILIA",
        "code_comm": "361",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B339",
        "postal_code": "20259",
        "nom_comm": "VALLICA",
        "code_comm": "339",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A098",
        "postal_code": "20138",
        "nom_comm": "COTI-CHIAVARI",
        "code_comm": "098",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B138",
        "postal_code": "20225",
        "nom_comm": "LAVATOGGIO",
        "code_comm": "138",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B153",
        "postal_code": "20245",
        "nom_comm": "MANSO",
        "code_comm": "153",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B225",
        "postal_code": "20230",
        "nom_comm": "PIETRA-DI-VERDE",
        "code_comm": "225",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B208",
        "postal_code": "20234",
        "nom_comm": "PERELLI",
        "code_comm": "208",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A249",
        "postal_code": "20110",
        "nom_comm": "PROPRIANO",
        "code_comm": "249",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B227",
        "postal_code": "20234",
        "nom_comm": "PIETRICAGGIO",
        "code_comm": "227",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B157",
        "postal_code": "20212",
        "nom_comm": "MAZZOLA",
        "code_comm": "157",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B134",
        "postal_code": "20220",
        "nom_comm": "L'ILE-ROUSSE",
        "code_comm": "134",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A100",
        "postal_code": "20126",
        "nom_comm": "CRISTINACCE",
        "code_comm": "100",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A284",
        "postal_code": "20140",
        "nom_comm": "SOLLACARO",
        "code_comm": "284",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A004",
        "postal_code": "20000",
        "nom_comm": "AJACCIO",
        "code_comm": "004",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B159",
        "postal_code": "20287",
        "nom_comm": "MERIA",
        "code_comm": "159",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B202",
        "postal_code": "20229",
        "nom_comm": "PARATA",
        "code_comm": "202",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B086",
        "postal_code": "20238",
        "nom_comm": "CENTURI",
        "code_comm": "086",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A024",
        "postal_code": "20116",
        "nom_comm": "AULLENE",
        "code_comm": "024",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A232",
        "postal_code": "20123",
        "nom_comm": "PILA-CANALE",
        "code_comm": "232",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A158",
        "postal_code": "20112",
        "nom_comm": "MELA",
        "code_comm": "158",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B239",
        "postal_code": "20232",
        "nom_comm": "POGGIO-D'OLETTA",
        "code_comm": "239",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B297",
        "postal_code": "20213",
        "nom_comm": "SAN-DAMIANO",
        "code_comm": "297",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B241",
        "postal_code": "20237",
        "nom_comm": "POGGIO-MARINACCIO",
        "code_comm": "241",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B287",
        "postal_code": "20246",
        "nom_comm": "SORIO",
        "code_comm": "287",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A018",
        "postal_code": "20110",
        "nom_comm": "ARBELLARA",
        "code_comm": "018",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B210",
        "postal_code": "20230",
        "nom_comm": "PERO-CASEVECCHIE",
        "code_comm": "210",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B218",
        "postal_code": "20251",
        "nom_comm": "PIEDICORTE-DI-GAGGIO",
        "code_comm": "218",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B120",
        "postal_code": "20600",
        "nom_comm": "FURIANI",
        "code_comm": "120",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A040",
        "postal_code": "20136",
        "nom_comm": "BOCOGNANO",
        "code_comm": "040",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B281",
        "postal_code": "20233",
        "nom_comm": "SISCO",
        "code_comm": "281",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B274",
        "postal_code": "20290",
        "nom_comm": "SCOLCA",
        "code_comm": "274",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B251",
        "postal_code": "20243",
        "nom_comm": "PRUNELLI-DI-FIUMORBO",
        "code_comm": "251",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B332",
        "postal_code": "20218",
        "nom_comm": "URTACA",
        "code_comm": "332",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B140",
        "postal_code": "20252",
        "nom_comm": "LENTO",
        "code_comm": "140",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B165",
        "postal_code": "20214",
        "nom_comm": "MONCALE",
        "code_comm": "165",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A062",
        "postal_code": "20133",
        "nom_comm": "CARBUCCIA",
        "code_comm": "062",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B010",
        "postal_code": "20220",
        "nom_comm": "ALGAJOLA",
        "code_comm": "010",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B183",
        "postal_code": "20217",
        "nom_comm": "OGLIASTRO",
        "code_comm": "183",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B192",
        "postal_code": "20290",
        "nom_comm": "OLMO",
        "code_comm": "192",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B223",
        "postal_code": "20218",
        "nom_comm": "PIETRALBA",
        "code_comm": "223",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B248",
        "postal_code": "20218",
        "nom_comm": "PRATO-DI-GIOVELLINA",
        "code_comm": "248",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B095",
        "postal_code": "20224",
        "nom_comm": "CORSCIA",
        "code_comm": "095",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B178",
        "postal_code": "20217",
        "nom_comm": "NONZA",
        "code_comm": "178",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B150",
        "postal_code": "20260",
        "nom_comm": "LUMIO",
        "code_comm": "150",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B291",
        "postal_code": "20229",
        "nom_comm": "STAZZONA",
        "code_comm": "291",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A099",
        "postal_code": "20148",
        "nom_comm": "COZZANO",
        "code_comm": "099",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B317",
        "postal_code": "20230",
        "nom_comm": "SANTA-REPARATA-DI-MORIANI",
        "code_comm": "317",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B350",
        "postal_code": "20290",
        "nom_comm": "VIGNALE",
        "code_comm": "350",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B242",
        "postal_code": "20230",
        "nom_comm": "POGGIO-MEZZANA",
        "code_comm": "242",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B226",
        "postal_code": "20251",
        "nom_comm": "PIETRASERENA",
        "code_comm": "226",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B180",
        "postal_code": "20226",
        "nom_comm": "NOVELLA",
        "code_comm": "180",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A300",
        "postal_code": "20170",
        "nom_comm": "SAN-GAVINO-DI-CARBINI",
        "code_comm": "300",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A056",
        "postal_code": "20142",
        "nom_comm": "CAMPO",
        "code_comm": "056",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A268",
        "postal_code": "20134",
        "nom_comm": "SAMPOLO",
        "code_comm": "268",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B290",
        "postal_code": "20226",
        "nom_comm": "SPELONCATO",
        "code_comm": "290",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B320",
        "postal_code": "20270",
        "nom_comm": "TALLONE",
        "code_comm": "320",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B036",
        "postal_code": "20252",
        "nom_comm": "BIGORNO",
        "code_comm": "036",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B096",
        "postal_code": "20250",
        "nom_comm": "CORTE",
        "code_comm": "096",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A363",
        "postal_code": "20112",
        "nom_comm": "ZOZA",
        "code_comm": "363",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B185",
        "postal_code": "20232",
        "nom_comm": "OLETTA",
        "code_comm": "185",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B068",
        "postal_code": "20244",
        "nom_comm": "CARTICASI",
        "code_comm": "068",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A017",
        "postal_code": "20167",
        "nom_comm": "APPIETTO",
        "code_comm": "017",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B341",
        "postal_code": "20231",
        "nom_comm": "VENACO",
        "code_comm": "341",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B217",
        "postal_code": "20229",
        "nom_comm": "PIAZZOLE",
        "code_comm": "217",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B161",
        "postal_code": "20270",
        "nom_comm": "MOITA",
        "code_comm": "161",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B054",
        "postal_code": "20290",
        "nom_comm": "CAMPILE",
        "code_comm": "054",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A031",
        "postal_code": "20119",
        "nom_comm": "BASTELICA",
        "code_comm": "031",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A115",
        "postal_code": "20100",
        "nom_comm": "FOCE",
        "code_comm": "115",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B012",
        "postal_code": "20251",
        "nom_comm": "ALTIANI",
        "code_comm": "012",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A322",
        "postal_code": "20134",
        "nom_comm": "TASSO",
        "code_comm": "322",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B286",
        "postal_code": "20213",
        "nom_comm": "SORBO-OCAGNANO",
        "code_comm": "286",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B136",
        "postal_code": "20218",
        "nom_comm": "LAMA",
        "code_comm": "136",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A200",
        "postal_code": "20134",
        "nom_comm": "PALNECA",
        "code_comm": "200",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B107",
        "postal_code": "20275",
        "nom_comm": "ERSA",
        "code_comm": "107",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B058",
        "postal_code": "20217",
        "nom_comm": "CANARI",
        "code_comm": "058",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B166",
        "postal_code": "20290",
        "nom_comm": "MONTE",
        "code_comm": "166",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B078",
        "postal_code": "20212",
        "nom_comm": "CASTELLARE-DI-MERCURIO",
        "code_comm": "078",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B207",
        "postal_code": "20213",
        "nom_comm": "PENTA-DI-CASINCA",
        "code_comm": "207",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B143",
        "postal_code": "20230",
        "nom_comm": "LINGUIZZETTA",
        "code_comm": "143",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A129",
        "postal_code": "20100",
        "nom_comm": "GROSSA",
        "code_comm": "129",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B072",
        "postal_code": "20215",
        "nom_comm": "CASALTA",
        "code_comm": "072",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A215",
        "postal_code": "20131",
        "nom_comm": "PIANOTTOLI-CALDARELLO",
        "code_comm": "215",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B334",
        "postal_code": "20234",
        "nom_comm": "VALLE-D'ALESANI",
        "code_comm": "334",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A209",
        "postal_code": "20167",
        "nom_comm": "PERI",
        "code_comm": "209",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B283",
        "postal_code": "20240",
        "nom_comm": "SOLARO",
        "code_comm": "283",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A228",
        "postal_code": "20166",
        "nom_comm": "PIETROSELLA",
        "code_comm": "228",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A349",
        "postal_code": "20110",
        "nom_comm": "VIGGIANELLO",
        "code_comm": "349",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B155",
        "postal_code": "20270",
        "nom_comm": "MATRA",
        "code_comm": "155",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B102",
        "postal_code": "20290",
        "nom_comm": "CROCICCHIA",
        "code_comm": "102",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A041",
        "postal_code": "20169",
        "nom_comm": "BONIFACIO",
        "code_comm": "041",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B039",
        "postal_code": "20235",
        "nom_comm": "BISINCHI",
        "code_comm": "039",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B234",
        "postal_code": "20234",
        "nom_comm": "PIOBETTA",
        "code_comm": "234",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A060",
        "postal_code": "20151",
        "nom_comm": "CANNELLE",
        "code_comm": "060",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B093",
        "postal_code": "20256",
        "nom_comm": "CORBARA",
        "code_comm": "093",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B298",
        "postal_code": "20217",
        "nom_comm": "SAINT-FLORENT",
        "code_comm": "298",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A269",
        "postal_code": "20145",
        "nom_comm": "SARI-SOLENZARA",
        "code_comm": "269",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A312",
        "postal_code": "20190",
        "nom_comm": "SANTA-MARIA-SICHE",
        "code_comm": "312",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B233",
        "postal_code": "20228",
        "nom_comm": "PINO",
        "code_comm": "233",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B304",
        "postal_code": "20244",
        "nom_comm": "SAN-LORENZO",
        "code_comm": "304",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A048",
        "postal_code": "20111",
        "nom_comm": "CALCATOGGIO",
        "code_comm": "048",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B145",
        "postal_code": "20215",
        "nom_comm": "LORETO-DI-CASINCA",
        "code_comm": "145",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A253",
        "postal_code": "20142",
        "nom_comm": "QUASQUARA",
        "code_comm": "253",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A131",
        "postal_code": "20160",
        "nom_comm": "GUAGNO",
        "code_comm": "131",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B013",
        "postal_code": "20212",
        "nom_comm": "ALZI",
        "code_comm": "013",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A008",
        "postal_code": "20128",
        "nom_comm": "ALBITRECCIA",
        "code_comm": "008",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B313",
        "postal_code": "20230",
        "nom_comm": "SAN-NICOLAO",
        "code_comm": "313",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B116",
        "postal_code": "20212",
        "nom_comm": "FOCICCHIA",
        "code_comm": "116",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B105",
        "postal_code": "20212",
        "nom_comm": "ERBAJOLO",
        "code_comm": "105",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B184",
        "postal_code": "20217",
        "nom_comm": "OLCANI",
        "code_comm": "184",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A360",
        "postal_code": "20190",
        "nom_comm": "ZIGLIARA",
        "code_comm": "360",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A262",
        "postal_code": "20121",
        "nom_comm": "ROSAZIA",
        "code_comm": "262",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A035",
        "postal_code": "20110",
        "nom_comm": "BELVEDERE-CAMPOMORO",
        "code_comm": "035",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B015",
        "postal_code": "20272",
        "nom_comm": "AMPRIANI",
        "code_comm": "015",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A118",
        "postal_code": "20143",
        "nom_comm": "FOZZANO",
        "code_comm": "118",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B243",
        "postal_code": "20229",
        "nom_comm": "POLVEROSO",
        "code_comm": "243",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A204",
        "postal_code": "20121",
        "nom_comm": "PASTRICCIOLA",
        "code_comm": "204",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A357",
        "postal_code": "20116",
        "nom_comm": "ZERUBIA",
        "code_comm": "357",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B110",
        "postal_code": "20212",
        "nom_comm": "FAVALELLO",
        "code_comm": "110",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A197",
        "postal_code": "20147",
        "nom_comm": "OSANI",
        "code_comm": "197",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A117",
        "postal_code": "20190",
        "nom_comm": "FORCIOLO",
        "code_comm": "117",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B122",
        "postal_code": "20218",
        "nom_comm": "GAVIGNANO",
        "code_comm": "122",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A133",
        "postal_code": "20153",
        "nom_comm": "GUITERA-LES-BAINS",
        "code_comm": "133",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A154",
        "postal_code": "20141",
        "nom_comm": "MARIGNANA",
        "code_comm": "154",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B296",
        "postal_code": "20220",
        "nom_comm": "SANT'ANTONINO",
        "code_comm": "296",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A085",
        "postal_code": "20117",
        "nom_comm": "CAURO",
        "code_comm": "085",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B002",
        "postal_code": "20270",
        "nom_comm": "AGHIONE",
        "code_comm": "002",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B264",
        "postal_code": "20244",
        "nom_comm": "RUSIO",
        "code_comm": "264",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B261",
        "postal_code": "20247",
        "nom_comm": "ROGLIANO",
        "code_comm": "261",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B023",
        "postal_code": "20276",
        "nom_comm": "ASCO",
        "code_comm": "023",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A006",
        "postal_code": "20167",
        "nom_comm": "ALATA",
        "code_comm": "006",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B055",
        "postal_code": "20252",
        "nom_comm": "CAMPITELLO",
        "code_comm": "055",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B307",
        "postal_code": "20230",
        "nom_comm": "SANTA-LUCIA-DI-MORIANI",
        "code_comm": "307",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B255",
        "postal_code": "20237",
        "nom_comm": "QUERCITELLO",
        "code_comm": "255",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B156",
        "postal_code": "20259",
        "nom_comm": "MAUSOLEO",
        "code_comm": "156",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B020",
        "postal_code": "20220",
        "nom_comm": "AREGNO",
        "code_comm": "020",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B260",
        "postal_code": "20250",
        "nom_comm": "RIVENTOSA",
        "code_comm": "260",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B121",
        "postal_code": "20245",
        "nom_comm": "GALERIA",
        "code_comm": "121",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B112",
        "postal_code": "20225",
        "nom_comm": "FELICETO",
        "code_comm": "112",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A038",
        "postal_code": "20100",
        "nom_comm": "BILIA",
        "code_comm": "038",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B314",
        "postal_code": "20246",
        "nom_comm": "SANTO-PIETRO-DI-TENDA",
        "code_comm": "314",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B176",
        "postal_code": "20229",
        "nom_comm": "NOCARIO",
        "code_comm": "176",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B167",
        "postal_code": "20214",
        "nom_comm": "MONTEGROSSO",
        "code_comm": "167",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B333",
        "postal_code": "20232",
        "nom_comm": "VALLECALLE",
        "code_comm": "333",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B337",
        "postal_code": "20235",
        "nom_comm": "VALLE-DI-ROSTINO",
        "code_comm": "337",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B199",
        "postal_code": "20226",
        "nom_comm": "PALASCA",
        "code_comm": "199",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B335",
        "postal_code": "20221",
        "nom_comm": "VALLE-DI-CAMPOLORO",
        "code_comm": "335",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A324",
        "postal_code": "20163",
        "nom_comm": "TAVERA",
        "code_comm": "324",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A001",
        "postal_code": "20167",
        "nom_comm": "AFA",
        "code_comm": "001",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B170",
        "postal_code": "20238",
        "nom_comm": "MORSIGLIA",
        "code_comm": "170",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B074",
        "postal_code": "20250",
        "nom_comm": "CASANOVA",
        "code_comm": "074",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B250",
        "postal_code": "20290",
        "nom_comm": "PRUNELLI-DI-CASACCONI",
        "code_comm": "250",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B007",
        "postal_code": "20224",
        "nom_comm": "ALBERTACCE",
        "code_comm": "007",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B303",
        "postal_code": "20230",
        "nom_comm": "SAN-GIULIANO",
        "code_comm": "303",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A348",
        "postal_code": "20160",
        "nom_comm": "VICO",
        "code_comm": "348",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A064",
        "postal_code": "20190",
        "nom_comm": "CARDO-TORGIA",
        "code_comm": "064",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B052",
        "postal_code": "20229",
        "nom_comm": "CAMPANA",
        "code_comm": "052",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A163",
        "postal_code": "20171",
        "nom_comm": "MONACIA-D'AULLENE",
        "code_comm": "163",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A272",
        "postal_code": "20100",
        "nom_comm": "SARTENE",
        "code_comm": "272",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A022",
        "postal_code": "20151",
        "nom_comm": "ARRO",
        "code_comm": "022",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B263",
        "postal_code": "20242",
        "nom_comm": "ROSPIGLIANI",
        "code_comm": "263",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A191",
        "postal_code": "20112",
        "nom_comm": "OLMICCIA",
        "code_comm": "191",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A258",
        "postal_code": "20160",
        "nom_comm": "RENNO",
        "code_comm": "258",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B152",
        "postal_code": "20228",
        "nom_comm": "LURI",
        "code_comm": "152",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B033",
        "postal_code": "20200/20600",
        "nom_comm": "BASTIA",
        "code_comm": "033",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B175",
        "postal_code": "20225",
        "nom_comm": "NESSA",
        "code_comm": "175",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B267",
        "postal_code": "20218",
        "nom_comm": "SALICETO",
        "code_comm": "267",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B069",
        "postal_code": "20237",
        "nom_comm": "CASABIANCA",
        "code_comm": "069",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A198",
        "postal_code": "20150",
        "nom_comm": "OTA",
        "code_comm": "198",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A186",
        "postal_code": "20140",
        "nom_comm": "OLIVESE",
        "code_comm": "186",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A092",
        "postal_code": "20135",
        "nom_comm": "CONCA",
        "code_comm": "092",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A271",
        "postal_code": "20167",
        "nom_comm": "SARROLA-CARCOPINO",
        "code_comm": "271",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B205",
        "postal_code": "20253",
        "nom_comm": "PATRIMONIO",
        "code_comm": "205",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B193",
        "postal_code": "20236",
        "nom_comm": "OMESSA",
        "code_comm": "193",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B003",
        "postal_code": "20244",
        "nom_comm": "AITI",
        "code_comm": "003",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B252",
        "postal_code": "20213",
        "nom_comm": "PRUNO",
        "code_comm": "252",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A108",
        "postal_code": "20126",
        "nom_comm": "EVISA",
        "code_comm": "108",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A028",
        "postal_code": "20160",
        "nom_comm": "BALOGNA",
        "code_comm": "028",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B123",
        "postal_code": "20240",
        "nom_comm": "GHISONACCIA",
        "code_comm": "123",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B088",
        "postal_code": "20230",
        "nom_comm": "CHIATRA",
        "code_comm": "088",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B256",
        "postal_code": "20229",
        "nom_comm": "RAPAGGIO",
        "code_comm": "256",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B083",
        "postal_code": "20236",
        "nom_comm": "CASTIRLA",
        "code_comm": "083",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A071",
        "postal_code": "20140",
        "nom_comm": "CASALABRIVA",
        "code_comm": "071",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B265",
        "postal_code": "20239",
        "nom_comm": "RUTALI",
        "code_comm": "265",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B168",
        "postal_code": "20220",
        "nom_comm": "MONTICELLO",
        "code_comm": "168",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B045",
        "postal_code": "20212",
        "nom_comm": "BUSTANICO",
        "code_comm": "045",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B277",
        "postal_code": "20243",
        "nom_comm": "SERRA-DI-FIUMORBO",
        "code_comm": "277",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A089",
        "postal_code": "20134",
        "nom_comm": "CIAMANNACCE",
        "code_comm": "089",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B366",
        "postal_code": "20240",
        "nom_comm": "CHISA",
        "code_comm": "366",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A358",
        "postal_code": "20173",
        "nom_comm": "ZEVACO",
        "code_comm": "358",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B318",
        "postal_code": "20230",
        "nom_comm": "TAGLIO-ISOLACCIO",
        "code_comm": "318",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A323",
        "postal_code": "20167",
        "nom_comm": "TAVACO",
        "code_comm": "323",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A065",
        "postal_code": "20130",
        "nom_comm": "CARGESE",
        "code_comm": "065",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B101",
        "postal_code": "20237",
        "nom_comm": "CROCE",
        "code_comm": "101",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B042",
        "postal_code": "20290",
        "nom_comm": "BORGO",
        "code_comm": "042",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B179",
        "postal_code": "20234",
        "nom_comm": "NOVALE",
        "code_comm": "179",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B025",
        "postal_code": "20225",
        "nom_comm": "AVAPESSA",
        "code_comm": "025",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A331",
        "postal_code": "20128",
        "nom_comm": "URBALACONE",
        "code_comm": "331",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B347",
        "postal_code": "20242",
        "nom_comm": "VEZZANI",
        "code_comm": "347",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B257",
        "postal_code": "20246",
        "nom_comm": "RAPALE",
        "code_comm": "257",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B081",
        "postal_code": "20218",
        "nom_comm": "CASTIGLIONE",
        "code_comm": "081",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B149",
        "postal_code": "20240",
        "nom_comm": "LUGO-DI-NAZZA",
        "code_comm": "149",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B077",
        "postal_code": "20213",
        "nom_comm": "CASTELLARE-DI-CASINCA",
        "code_comm": "077",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A308",
        "postal_code": "20112",
        "nom_comm": "SAINTE-LUCIE-DE-TALLANO",
        "code_comm": "308",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B340",
        "postal_code": "20230",
        "nom_comm": "VELONE-ORNETO",
        "code_comm": "340",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B222",
        "postal_code": "20229",
        "nom_comm": "PIE-D'OREZZA",
        "code_comm": "222",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B273",
        "postal_code": "20213",
        "nom_comm": "SCATA",
        "code_comm": "273",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A279",
        "postal_code": "20147",
        "nom_comm": "SERRIERA",
        "code_comm": "279",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B172",
        "postal_code": "20239",
        "nom_comm": "MURATO",
        "code_comm": "172",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B206",
        "postal_code": "20290",
        "nom_comm": "PENTA-ACQUATELLA",
        "code_comm": "206",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B057",
        "postal_code": "20230",
        "nom_comm": "CANALE-DI-VERDE",
        "code_comm": "057",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B213",
        "postal_code": "20272",
        "nom_comm": "PIANELLO",
        "code_comm": "213",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B229",
        "postal_code": "20242",
        "nom_comm": "PIETROSO",
        "code_comm": "229",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B195",
        "postal_code": "20290",
        "nom_comm": "ORTIPORIO",
        "code_comm": "195",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A144",
        "postal_code": "20139",
        "nom_comm": "LOPIGNA",
        "code_comm": "144",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A021",
        "postal_code": "20140",
        "nom_comm": "ARGIUSTA-MORICCIO",
        "code_comm": "021",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B289",
        "postal_code": "20250",
        "nom_comm": "SOVERIA",
        "code_comm": "289",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A061",
        "postal_code": "20170",
        "nom_comm": "CARBINI",
        "code_comm": "061",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B049",
        "postal_code": "20214",
        "nom_comm": "CALENZANA",
        "code_comm": "049",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B235",
        "postal_code": "20259",
        "nom_comm": "PIOGGIOLA",
        "code_comm": "235",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B126",
        "postal_code": "20251",
        "nom_comm": "GIUNCAGGIO",
        "code_comm": "126",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A127",
        "postal_code": "20100",
        "nom_comm": "GIUNCHETO",
        "code_comm": "127",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B338",
        "postal_code": "20229",
        "nom_comm": "VALLE-D'OREZZA",
        "code_comm": "338",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B220",
        "postal_code": "20218",
        "nom_comm": "PIEDIGRIGGIO",
        "code_comm": "220",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B275",
        "postal_code": "20212",
        "nom_comm": "SERMANO",
        "code_comm": "275",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A019",
        "postal_code": "20160",
        "nom_comm": "ARBORI",
        "code_comm": "019",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B059",
        "postal_code": "20235",
        "nom_comm": "CANAVAGGIA",
        "code_comm": "059",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B005",
        "postal_code": "20212",
        "nom_comm": "ALANDO",
        "code_comm": "005",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B301",
        "postal_code": "20246",
        "nom_comm": "SAN-GAVINO-DI-TENDA",
        "code_comm": "301",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B043",
        "postal_code": "20222",
        "nom_comm": "BRANDO",
        "code_comm": "043",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B364",
        "postal_code": "20272",
        "nom_comm": "ZUANI",
        "code_comm": "364",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B319",
        "postal_code": "20230",
        "nom_comm": "TALASANI",
        "code_comm": "319",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A336",
        "postal_code": "20167",
        "nom_comm": "VALLE-DI-MEZZANA",
        "code_comm": "336",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A285",
        "postal_code": "20152",
        "nom_comm": "SORBOLLANO",
        "code_comm": "285",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B053",
        "postal_code": "20270",
        "nom_comm": "CAMPI",
        "code_comm": "053",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B173",
        "postal_code": "20225",
        "nom_comm": "MURO",
        "code_comm": "173",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B075",
        "postal_code": "20270",
        "nom_comm": "CASEVECCHIE",
        "code_comm": "075",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B355",
        "postal_code": "20290",
        "nom_comm": "VOLPAJOLA",
        "code_comm": "355",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B080",
        "postal_code": "20218",
        "nom_comm": "CASTIFAO",
        "code_comm": "080",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B016",
        "postal_code": "20270",
        "nom_comm": "ANTISANTI",
        "code_comm": "016",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A345",
        "postal_code": "20172",
        "nom_comm": "VERO",
        "code_comm": "345",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B305",
        "postal_code": "20200",
        "nom_comm": "SAN-MARTINO-DI-LOTA",
        "code_comm": "305",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B182",
        "postal_code": "20226",
        "nom_comm": "OCCHIATANA",
        "code_comm": "182",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A014",
        "postal_code": "20151",
        "nom_comm": "AMBIEGNA",
        "code_comm": "014",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A288",
        "postal_code": "20146",
        "nom_comm": "SOTTA",
        "code_comm": "288",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B316",
        "postal_code": "20220",
        "nom_comm": "SANTA-REPARATA-DI-BALAGNA",
        "code_comm": "316",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B309",
        "postal_code": "20200",
        "nom_comm": "SANTA-MARIA-DI-LOTA",
        "code_comm": "309",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A330",
        "postal_code": "20133",
        "nom_comm": "UCCIANI",
        "code_comm": "330",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A254",
        "postal_code": "20122",
        "nom_comm": "QUENZA",
        "code_comm": "254",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B051",
        "postal_code": "20244",
        "nom_comm": "CAMBIA",
        "code_comm": "051",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B311",
        "postal_code": "20221",
        "nom_comm": "SANTA-MARIA-POGGIO",
        "code_comm": "311",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B216",
        "postal_code": "20234",
        "nom_comm": "PIAZZALI",
        "code_comm": "216",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B148",
        "postal_code": "20290",
        "nom_comm": "LUCCIANA",
        "code_comm": "148",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A276",
        "postal_code": "20140",
        "nom_comm": "SERRA-DI-FERRO",
        "code_comm": "276",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B329",
        "postal_code": "20250",
        "nom_comm": "TRALONCA",
        "code_comm": "329",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A351",
        "postal_code": "20167",
        "nom_comm": "VILLANOVA",
        "code_comm": "351",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B162",
        "postal_code": "20218",
        "nom_comm": "MOLTIFAO",
        "code_comm": "162",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A142",
        "postal_code": "20170",
        "nom_comm": "LEVIE",
        "code_comm": "142",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B352",
        "postal_code": "20279",
        "nom_comm": "VILLE-DI-PARASO",
        "code_comm": "352",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A240",
        "postal_code": "20125",
        "nom_comm": "POGGIOLO",
        "code_comm": "240",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A196",
        "postal_code": "20125",
        "nom_comm": "ORTO",
        "code_comm": "196",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B047",
        "postal_code": "20224",
        "nom_comm": "CALACUCCIA",
        "code_comm": "047",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B164",
        "postal_code": "20229",
        "nom_comm": "MONACIA-D'OREZZA",
        "code_comm": "164",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B109",
        "postal_code": "20253",
        "nom_comm": "FARINOLE",
        "code_comm": "109",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B046",
        "postal_code": "20228",
        "nom_comm": "CAGNANO",
        "code_comm": "046",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A362",
        "postal_code": "20124",
        "nom_comm": "ZONZA",
        "code_comm": "362",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B244",
        "postal_code": "20218",
        "nom_comm": "POPOLASCA",
        "code_comm": "244",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A146",
        "postal_code": "20165",
        "nom_comm": "LORETO-DI-TALLANO",
        "code_comm": "146",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A114",
        "postal_code": "20114",
        "nom_comm": "FIGARI",
        "code_comm": "114",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B171",
        "postal_code": "20219",
        "nom_comm": "MURACCIOLE",
        "code_comm": "171",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A295",
        "postal_code": "20151",
        "nom_comm": "SANT'ANDREA-D'ORCINO",
        "code_comm": "295",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B346",
        "postal_code": "20215",
        "nom_comm": "VESCOVATO",
        "code_comm": "346",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B034",
        "postal_code": "20226",
        "nom_comm": "BELGODERE",
        "code_comm": "034",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B097",
        "postal_code": "20226",
        "nom_comm": "COSTA",
        "code_comm": "097",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B137",
        "postal_code": "20244",
        "nom_comm": "LANO",
        "code_comm": "137",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B135",
        "postal_code": "20243",
        "nom_comm": "ISOLACCIO-DI-FIUMORBO",
        "code_comm": "135",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B082",
        "postal_code": "20218",
        "nom_comm": "CASTINETA",
        "code_comm": "082",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A011",
        "postal_code": "20112",
        "nom_comm": "ALTAGENE",
        "code_comm": "011",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A181",
        "postal_code": "20117",
        "nom_comm": "OCANA",
        "code_comm": "181",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A160",
        "postal_code": "20140",
        "nom_comm": "MOCA-CROCE",
        "code_comm": "160",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B187",
        "postal_code": "20217",
        "nom_comm": "OLMETA-DI-CAPOCORSO",
        "code_comm": "187",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B113",
        "postal_code": "20237",
        "nom_comm": "FICAJA",
        "code_comm": "113",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A070",
        "postal_code": "20111",
        "nom_comm": "CASAGLIONE",
        "code_comm": "070",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A189",
        "postal_code": "20113",
        "nom_comm": "OLMETO",
        "code_comm": "189",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2A203",
        "postal_code": "20147",
        "nom_comm": "PARTINELLO",
        "code_comm": "203",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B246",
        "postal_code": "20237",
        "nom_comm": "LA PORTA",
        "code_comm": "246",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A310",
        "postal_code": "20143",
        "nom_comm": "SANTA-MARIA-FIGANIELLA",
        "code_comm": "310",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B231",
        "postal_code": "20220",
        "nom_comm": "PIGNA",
        "code_comm": "231",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B344",
        "postal_code": "20229",
        "nom_comm": "VERDESE",
        "code_comm": "344",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B037",
        "postal_code": "20620",
        "nom_comm": "BIGUGLIA",
        "code_comm": "037",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A104",
        "postal_code": "20117",
        "nom_comm": "ECCICA-SUARELLA",
        "code_comm": "104",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B050",
        "postal_code": "20260",
        "nom_comm": "CALVI",
        "code_comm": "050",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B219",
        "postal_code": "20229",
        "nom_comm": "PIEDICROCE",
        "code_comm": "219",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B315",
        "postal_code": "20250",
        "nom_comm": "SANTO-PIETRO-DI-VENACO",
        "code_comm": "315",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B356",
        "postal_code": "20272",
        "nom_comm": "ZALANA",
        "code_comm": "356",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B190",
        "postal_code": "20259",
        "nom_comm": "OLMI-CAPPELLA",
        "code_comm": "190",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A103",
        "postal_code": "20167",
        "nom_comm": "CUTTOLI-CORTICCHIATO",
        "code_comm": "103",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B354",
        "postal_code": "20219",
        "nom_comm": "VIVARIO",
        "code_comm": "354",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A270",
        "postal_code": "20151",
        "nom_comm": "SARI-D'ORCINO",
        "code_comm": "270",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B079",
        "postal_code": "20235",
        "nom_comm": "CASTELLO-DI-ROSTINO",
        "code_comm": "079",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A119",
        "postal_code": "20157",
        "nom_comm": "FRASSETO",
        "code_comm": "119",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B299",
        "postal_code": "20213",
        "nom_comm": "SAN-GAVINO-D'AMPUGNANI",
        "code_comm": "299",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A174",
        "postal_code": "20160",
        "nom_comm": "MURZO",
        "code_comm": "174",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B067",
        "postal_code": "20229",
        "nom_comm": "CARPINETO",
        "code_comm": "067",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2A130",
        "postal_code": "20128",
        "nom_comm": "GROSSETO-PRUGNA",
        "code_comm": "130",
        "code_dept": "2A",
        "code_reg": "94",
    },
    {
        "insee_com": "2B087",
        "postal_code": "20221",
        "nom_comm": "CERVIONE",
        "code_comm": "087",
        "code_dept": "2B",
        "code_reg": "94",
    },
    {
        "insee_com": "2B111",
        "postal_code": "20234",
        "nom_comm": "FELCE",
        "code_comm": "111",
        "code_dept": "2B",
        "code_reg": "94",
    },
]
