name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8

      - name: Setup Pre-commit
        uses: pre-commit/action@v3.0.0

      - uses: pre-commit-ci/lite-action@v1.0.1
        if: always()
