name: "Test and deploy to staging"
on:
  push:
    branches:
      - main


# Explicitely set permissions to allow Dependabot workflow runs to write in the PR
# for coverage's reporting.
# By default, these are read-only when the actions are ran by Dependabot
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions
permissions:
  pull-requests: write

env:
  DATABASE_URL: postgres://apilos:apilos@localhost:5432/apilos
  DB_READONLY: postgres://apilos:apilos@localhost:5432/apilos
  SECRET_KEY: secret-key
  DEBUG: False

jobs:
  coverage:
    name: Test & Coverage

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: apilos
          POSTGRES_NAME: apilos
          POSTGRES_HOST: postgres
          POSTGRES_PASSWORD: apilos
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt -r dev-requirements.txt
      - name: Check migrations
        run: |
          python manage.py makemigrations --check --dry-run
      - name: Execute test
        run: |
          python manage.py test
      - uses: kolok/deploy-to-scalingo@v1
        with:
          ssh-private-key: ${{ secrets.SCALINGO_SSH_PRIVATE_KEY }}
          app-name: apilos-staging
          known-host: ssh.osc-fr1.scalingo.com
      - uses: kolok/deploy-to-scalingo@v1
        with:
          ssh-private-key: ${{ secrets.SCALINGO_SSH_PRIVATE_KEY }}
          app-name: apilos-siap-integration
          known-host: ssh.osc-fr1.scalingo.com
