name: Deploy Sphinx Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to your default branch name, if necessary
      - sphynx

jobs:
  publish_docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"

      - name: Install dependencies
        run: |
          pip install pip-tools
          pip install -r doc-requirements.txt

      - name: Build the documentation
        run: sphinx-build -M html docs _build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
