name: 'coverage'
on:
  - pull_request

jobs:
  coverage:
    name: Test & Coverage

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: apilos
          POSTGRES_NAME: apilos
          POSTGRES_HOST: postgres
          POSTGRES_PASSWORD: apilos
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Create ecolotest database
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client
          PGPASSWORD=apilos psql -h localhost -U apilos -d apilos -c "create database ecolotest;"
          PGPASSWORD=apilos psql -h localhost -U apilos -d ecolotest -c "create schema ecolo;"
      - name: Install dependencies
        run:
          pip install -r requirements.txt -r dev-requirements.txt
      - name: Execute test with coverage
        run: |
          cp .env.template .env.test
          coverage run --source='.' manage.py test
        env:
          DB_HOST: localhost
          ECOLO_DATABASE_URL: postgres://apilos:apilos@localhost:5432/ecolotest?currentSchema=ecolo
      - name: Create coverage report
        run:
          coverage xml -o coverage.xml
      - name: Post coverage to PR
        uses: orgoro/coverage@v3
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          thresholdAll: 0.6
          thresholdNew: 0.5
          thresholdModified: 0.4
