name: 'coverage'
on:
  - pull_request

jobs:
  coverage:
    name: Test & Coverage
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run:
          pip install -r requirements.txt -r dev-requirements.txt
      - name: Execute test with coverage
        run:
          coverage run --source='.' manage.py test
      - name: Create coverage report
        run:
          coverage xml coverage.xml
      - name: Post coverage to PR
        uses: orgoro/coverage@v3
        with:
          coverageFile: .coverage
          token: ${{ secrets.GITHUB_TOKEN }}
