name: "Test and deploy to staging"
on:
  push:
    branches:
      - main

env:
  DATABASE_URL: postgres://apilos:apilos@localhost:5432/apilos
  DB_READONLY: postgres://apilos:apilos@localhost:5432/apilos
  SECRET_KEY: secret-key
  DEBUG: False

jobs:
  check:
    uses: ./.github/workflows/run_check.yml

  test:
    uses: ./.github/workflows/run_tests.yml

  deploy_to_siap_integration:
    name: "Deploy to Siap Integration"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: kolok/deploy-to-scalingo@v1
        with:
          ssh-private-key: ${{ secrets.SCALINGO_SSH_PRIVATE_KEY }}
          app-name: apilos-siap-integration
          known-host: ssh.osc-fr1.scalingo.com
