#fixme : we will need to do it for production and siap-production
name: Backup S3 Staging bucket

on:
  # Any push to test, fixme : to be removed
  push:
  schedule:
    # At 1:31 every Monday
    - cron: '31 1 * * 1'

env:
  S3_HOST: https://s3.fr-par.scw.cloud
  S3_BUCKET: s3://apilos-staging
  BACKUP_NAME: staging

jobs:
  backup-staging:
    name: Backup S3 in Staging environment
    runs-on: ubuntu-latest


    steps:
      - name: Backup
        run: |
          pip install s3cmd
          s3cmd --host=${{ env.S3_HOST }} --access_key=${{ secrets.S3_ACCESS_KEY }} --secret_key=${{ secrets.S3_SECRET_KEY }} ls
          s3cmd --host=${{ env.S3_HOST }} --access_key=${{ secrets.S3_ACCESS_KEY }} --secret_key=${{ secrets.S3_SECRET_KEY }} sync --dry-run ${{ env.S3_BUCKET }} ${{ env.BACKUP_NAME }}
#          tar cfz ${{ env.BACKUP_NAME }}.tar.gz ${{ env.BACKUP_NAME }}
